// components/Tabs/vue/Tabs.vue
<script lang="ts" setup>
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { Tab, throttle, variants } from '@cypress-design/constants-tabs'

const props = withDefaults(
  defineProps<{
    /**
     * The tabs to display
     */
    tabs: Tab[]
    /**
     * The active tab
     */
    activeId?: string
    /**
     * Appearance of tabs
     */
    variant?: keyof typeof variants
  }>(),
  {
    variant: 'default',
  },
)

const $tab = ref<HTMLButtonElement[]>()

const emit = defineEmits<{
  /**
   * A tab is changed
   * @param tab new tab selected
   */
  (event: 'switch', tab: Tab): void
  (event: 'update:activeId', tab: string): void
}>()

const activeId = ref(props.activeId ?? props.tabs.find((tab) => tab.active)?.id)

watch(
  () => props.activeId,
  (id) => {
    activeId.value = id
  },
)

const activeMarkerStyle = ref<
  { left?: string; width?: string; transitionProperty?: string } | undefined
>()

function updateActiveMarkerStyle() {
  const activeIndex = props.tabs.findIndex((tab) => tab.id === activeId.value)
  if (activeIndex > -1) {
    const activeTab = $tab.value?.[activeIndex]
    if (activeTab) {
      activeMarkerStyle.value = {
        ...activeMarkerStyle.value,
        left: `${activeTab.offsetLeft}px`,
        width: `${activeTab.offsetWidth}px`,
      }
    }
  }
}

const throttledUpdateActiveMarkerStyle = throttle(updateActiveMarkerStyle, 100)

onMounted(() => {
  watch(
    activeId,
    () => {
      updateActiveMarkerStyle()
    },
    { immediate: true },
  )

  // Only start animation after the first render
  nextTick(() => {
    activeMarkerStyle.value = {
      ...activeMarkerStyle.value,
      transitionProperty: 'left, width',
    }
  })
})

onMounted(() => {
  window.addEventListener('resize', throttledUpdateActiveMarkerStyle)
})

onUnmounted(() => {
  window.removeEventListener('resize', throttledUpdateActiveMarkerStyle)
})

function navigate(shift: number) {
  const shiftedIndex =
    props.tabs.findIndex((tab) => tab.id === activeId.value) + shift
  const nextIndex =
    shiftedIndex < 0
      ? props.tabs.length - 1
      : shiftedIndex >= props.tabs.length
      ? 0
      : shiftedIndex
  activeId.value = props.tabs[nextIndex].id
  $tab.value?.[nextIndex]?.focus()
  emit('update:activeId', props.tabs[nextIndex].id)
  emit('switch', props.tabs[nextIndex])
}

const classes = computed(() => {
  if (props.variant in variants) {
    return variants[props.variant].classes
  }
  return variants.default.classes
})

const iconProps = computed(() => {
  if (props.variant in variants) {
    return variants[props.variant].icon
  }
  return variants.default.icon
})
</script>

<template>
  <div role="tablist" :class="classes.wrapper">
    <div v-if="'subWrapper' in classes" :class="classes.subWrapper" />
    <template>
      <component
        v-for="{
          id,
          href,
          label,
          tag,
          icon,
          iconBefore,
          iconAfter,
          ...dataAttr
        } in tabs"
        :key="id"
        :is="href ? 'a' : 'button'"
        :href="href"
        ref="$tab"
        role="tab"
        :tabindex="id === activeId ? undefined : -1"
        :aria-selected="id === activeId ? true : undefined"
        :class="[
          classes.button,
          {
            [classes.activeStatic]: id === activeId && !activeMarkerStyle,
            [classes.active]: id === activeId,
            [classes.inActive]: id !== activeId,
          },
        ]"
        v-bind="dataAttr"
        @click="
          (e: MouseEvent) => {
            if (e.ctrlKey || e.metaKey) return
            e.preventDefault()
            activeId = id
            emit('switch', {
              id,
              href,
              label,
              tag,
              icon,
              iconBefore,
              iconAfter,
              ...dataAttr,
            })
          }
        "
        @keyup.left="navigate(-1)"
        @keyup.right="navigate(1)"
      >
        <!-- @slot render a tab with a custom scoped slot -->
        <slot
          name="tab"
          v-bind="{
            id,
            href,
            label,
            tag,
            icon,
            iconBefore,
            iconAfter,
            ...dataAttr,
          }"
        >
          <component
            v-if="iconBefore ?? icon"
            :is="iconBefore ?? icon"
            v-bind="iconProps"
            class="mr-[8px]"
          />
          {{ label }}
          <div v-if="tag" :class="classes.tag">{{ tag }}</div>
          <component
            v-if="iconAfter"
            :is="iconAfter"
            v-bind="iconProps"
            class="ml-[8px]"
          />
        </slot>
        <div
          v-if="id === activeId && !activeMarkerStyle"
          :class="classes.activeMarkerStatic"
        />
      </component>
    </template>
    <template v-if="activeMarkerStyle">
      <div
        :class="[classes.activeMarker, classes.activeMarkerColor]"
        :style="activeMarkerStyle"
      />
      <div
        :class="[classes.activeMarker, classes.activeMarkerBlender]"
        :style="activeMarkerStyle"
      />
    </template>
  </div>
</template>

// components/Tabs/react/Tabs.tsx
import * as React from 'react'
import clsx from 'clsx'
import { Tab, variants, throttle } from '@cypress-design/constants-tabs'

export interface TabsProps {
  /**
   * The tabs to display
   */
  tabs: Tab[]
  /**
   * The id of the active tab
   */
  activeId?: string
  /**
   * Appearance of tabs
   */
  variant?: keyof typeof variants
  /**
   * Callback when tab is changed
   * @param tab new tab selected
   */
  onSwitch?: (tab: Tab) => void

  /**
   * render a tab with a custom function
   */
  renderTab?: (tab: Tab) => React.ReactNode
}

export const Tabs: React.FC<TabsProps & React.HTMLProps<HTMLDivElement>> = ({
  tabs,
  onSwitch,
  variant = 'default',
  activeId: activeIdProp,
  renderTab,
  ...rest
}) => {
  const [mounted, setMounted] = React.useState(false)
  const [activeId, setActiveId] = React.useState(
    activeIdProp || tabs.find((tab) => tab.active)?.id,
  )

  React.useEffect(() => {
    if (mounted && activeIdProp) {
      setActiveId(activeIdProp)
    }
  }, [activeIdProp])

  const $tab = React.useRef<(HTMLButtonElement | HTMLAnchorElement)[]>([])

  const [activeMarkerStyle, setActiveMarkerStyle] = React.useState<{
    left?: string
    width?: string
    transitionProperty?: string
  }>({})

  function updateActiveMarkerStyle() {
    const activeTab = tabs.findIndex((tab) => tab.id === activeId)
    if (activeTab > -1) {
      const activeTabEl = $tab.current?.[activeTab]
      if (activeTabEl) {
        setActiveMarkerStyle({
          left: `${activeTabEl.offsetLeft}px`,
          width: `${activeTabEl.offsetWidth}px`,
          transitionProperty: 'left, width',
        })
      }
    }
    setMounted(true)
  }

  React.useEffect(() => {
    updateActiveMarkerStyle()
  }, [activeId])

  const throttledUpdateActiveMarkerStyle = throttle(
    updateActiveMarkerStyle,
    100,
  )

  React.useEffect(() => {
    window.addEventListener('resize', throttledUpdateActiveMarkerStyle)
    return () =>
      window.removeEventListener('resize', throttledUpdateActiveMarkerStyle)
  }, [])

  function navigate(shift: number) {
    const shiftedIndex = tabs.findIndex((tab) => tab.id === activeId) + shift
    const nextIndex =
      shiftedIndex < 0
        ? tabs.length - 1
        : shiftedIndex >= tabs.length
        ? 0
        : shiftedIndex
    setActiveId(tabs[nextIndex].id)
    $tab.current?.[nextIndex]?.focus()
    onSwitch?.(tabs[nextIndex])
  }

  const classes =
    variant in variants ? variants[variant].classes : variants.default.classes

  const iconProps =
    variant in variants ? variants[variant].icon : variants.default.icon

  return (
    <div role="tablist" className={classes.wrapper} {...rest}>
      {'subWrapper' in classes ? <div className={classes.subWrapper} /> : null}
      {tabs.map((tab, index) => {
        const ButtonTag = tab.href ? 'a' : 'button'
        const {
          id,
          href,
          icon,
          iconBefore,
          iconAfter: IconAfter,
          label,
          tag,
          ...dataAttr
        } = tab
        return (
          <ButtonTag
            key={id}
            role="tab"
            href={href}
            className={clsx([
              classes.button,
              {
                [classes.activeStatic]: id === activeId && !mounted,
                [classes.active]: id === activeId,
                [classes.inActive]: id !== activeId,
              },
            ])}
            // @ts-expect-error React is incapable of typing this kind of ref so we do not add a type
            ref={(el) => (el ? ($tab.current[index] = el) : null)}
            tabIndex={id === activeId ? undefined : -1}
            aria-selected={id === activeId ? true : undefined}
            onClick={(e) => {
              if (e.ctrlKey || e.metaKey) return
              e.preventDefault()
              setActiveId(id)
              onSwitch?.(tab)
            }}
            onKeyUp={(e) => {
              if (e.key === 'ArrowRight') {
                navigate(1)
              } else if (e.key === 'ArrowLeft') {
                navigate(-1)
              }
            }}
            {...dataAttr}
          >
            {renderTab ? (
              renderTab(tab)
            ) : (
              <>
                {(() => {
                  const IconBefore = iconBefore ?? icon
                  return IconBefore ? (
                    <IconBefore {...iconProps} className="mr-[8px]" />
                  ) : null
                })()}
                {label}
                {tag ? <div className={classes.tag}>{tag}</div> : null}
                {IconAfter ? (
                  <IconAfter {...iconProps} className="ml-[8px]" />
                ) : null}
              </>
            )}
            {id === activeId && !activeMarkerStyle.left ? (
              <div className={classes.activeMarkerStatic} />
            ) : null}
          </ButtonTag>
        )
      })}
      <div
        key="active-marker"
        className={clsx(classes.activeMarker, classes.activeMarkerColor)}
        style={activeMarkerStyle}
      />
      <div
        key="active-marker-blend"
        className={clsx(classes.activeMarker, classes.activeMarkerBlender)}
        style={activeMarkerStyle}
      />
    </div>
  )
}

export default Tabs
