// components/DocMenu/vue/_DocLink.vue
<script lang="ts" setup>
import type { NavItemLink } from '@cypress-design/constants-docmenu'

withDefaults(
  defineProps<{
    item: NavItemLink
    depth?: number
    collapsible: boolean
  }>(),
  {
    depth: -1,
  },
)
</script>

<template>
  <li
    class="list-none p-0"
    :class="{
      'pl-[16px]': depth >= 0,
    }"
  >
    <a
      class="group relative block w-full pl-[24px]"
      :class="{
        'text-indigo-500': item.active,
        'py-[8px] text-[16px] leading-[24px]': depth < 0,
        'leading-[20px] text-[14px] py-[12px]': depth >= 0,
      }"
      :href="item.href"
    >
      <div
        v-if="depth >= 0"
        class="absolute h-[80%] top-[10%] w-[4px] z-10 rounded-full hidden"
        :class="{
          'group-hover:block bg-gray-300': !item.active && collapsible,
        }"
        :style="{
          left: `-${18.5 + depth * 7.5}px`,
        }"
      />
      {{ item.label }}
    </a>
  </li>
</template>

// components/DocMenu/react/_DocLink.tsx
import * as React from 'react'
import clsx from 'clsx'
import { NavItemLink } from '@cypress-design/constants-docmenu'

export interface DocLinkProps {
  item: NavItemLink
  collapsible: boolean
  depth?: number
  onActive?: (top: number) => void
}

export const DocLink: React.FC<DocLinkProps> = ({
  item,
  collapsible,
  depth = -1,
  onActive,
}) => {
  const activeLIRef = React.useRef<HTMLLIElement>(null)

  // on mount, if the item is active,
  // send the top position to the parent
  React.useEffect(() => {
    if (item.active) {
      onActive?.(activeLIRef?.current?.offsetTop || 0)
    }
  })

  return (
    <li
      ref={activeLIRef}
      className={clsx('list-none p-0', {
        'pl-[16px]': depth >= 0,
      })}
    >
      <a
        className={clsx('group relative inline-block pl-[24px]', {
          'text-indigo-500': item.active,
          'py-[8px] text-[16px] leading-[24px]': depth < 0,
          'py-[12px] leading-[20px] text-[14px]': depth >= 0,
        })}
        href={item.href}
      >
        {depth >= 0 ? (
          <div
            className={clsx(
              'absolute w-[4px] z-10 top-[10%] h-[80%] rounded-full hidden',
              {
                'group-hover:block bg-gray-300': !item.active && collapsible,
              },
            )}
            style={{
              left: `-${18.5 + depth * 8}px`,
            }}
          />
        ) : null}
        {item.text}
      </a>
    </li>
  )
}
