// components/Select/vue/Select.vue
<script lang="ts" setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import Button from '@cypress-design/vue-button'
import { IconChevronDownSmall } from '@cypress-design/vue-icon'
import * as SelectConstants from '@cypress-design/constants-select'
import type {
  SelectItem,
  SelectAlignment,
  ButtonVariantLoose,
  SelectThemingProps,
  SelectHeaderProps,
  SelectSearchProps,
  SelectFooterProps,
  SelectSizingProps,
} from '@cypress-design/constants-select'
import SelectOptionList from './_SelectOptionList.vue'
import {
  filterAndCollapseHeadlines,
  getSelectableIndices,
} from './filter-items'

// Public props are composed from the shared groups in `constants-select`
// so the surface stays in sync with SelectOptionList / SelectOptionItem.
// Select-only fields (model value, open state, trigger override, etc.)
// are intersected in directly below.
type SelectComponentProps = SelectThemingProps &
  SelectHeaderProps &
  SelectSearchProps &
  SelectFooterProps &
  SelectSizingProps & {
    align?: SelectAlignment
    triggerVariant?: ButtonVariantLoose
    items: SelectItem[]
    modelValue?: string
    value?: string
    placeholder?: string
    disabled?: boolean
    defaultOpen?: boolean
    open?: boolean
    id?: string
    popoverClass?: string
  }

const props = withDefaults(defineProps<SelectComponentProps>(), {
  theme: SelectConstants.DefaultTheme,
  size: SelectConstants.DefaultSize,
  align: SelectConstants.DefaultAlignment,
  triggerVariant: SelectConstants.DefaultTriggerVariant,
  searchable: false,
  // Vue 3 quirk: Boolean props bound via `v-bind` with `undefined` are
  // cast to `false` BEFORE the child's withDefaults applies. Without an
  // explicit default here, omitting `searchFilters` at the call site
  // means Select forwards `false` to SelectOptionList, disabling the
  // filter (the row stays visual-only). Default true so search actually
  // filters by default.
  searchFilters: true,
  disabled: false,
  defaultOpen: false,
})

// `value` is `undefined` when the selection is cleared — happens when a
// checkbox row is re-clicked (toggle off). Consumers must handle both cases.
const emit = defineEmits<{
  (e: 'update:modelValue', value: string | undefined): void
  (e: 'update:open', open: boolean): void
  (e: 'change', value: string | undefined, item: SelectItem): void
  (e: 'header-tab-change', id: string): void
}>()

defineSlots<{
  trigger?: (ctx: {
    open: boolean
    selected: SelectItem | null
    toggle: () => void
    close: () => void
  }) => unknown
  footer?: () => unknown
}>()

// ---------- ids ----------
let uidCounter = 0
const uid = `cy-select-${++uidCounter}`
const popoverId = computed(() =>
  props.id ? `${props.id}-popover` : `${uid}-popover`,
)
const itemIdPrefix = computed(() =>
  props.id ? `${props.id}-opt` : `${uid}-opt`,
)

// ---------- open state ----------
// Note: Vue normalizes absent Boolean props to `false`, so we can't reliably
// distinguish "consumer didn't pass `open`" from "consumer passed `open=false`".
// We use internal state as the single source of truth: `open` and `defaultOpen`
// both seed the initial value, and updates flow out via `update:open`. A
// consumer that wants to force-close the popover can re-key the component.
const internalOpen = ref(props.open || props.defaultOpen)
const open = computed(() => internalOpen.value)
function setOpen(next: boolean) {
  internalOpen.value = next
  emit('update:open', next)
}

// ---------- selected value ----------
// Sticky-toward-controlled: once we ever see a defined `value` or
// `modelValue` prop the component is "controlled" and stays that way.
// This is the only discriminator that handles every common pattern:
// pure uncontrolled (no v-model / `value`), pure controlled (initial
// defined), lazy controlled (v-model bound to a ref that starts
// `undefined` and is later set), controlled clear (parent sets the
// value back to `undefined`), and checkbox toggle-off (component
// emits `undefined`). In every case the prop wins once observed, so
// a clear correctly shows the placeholder instead of falling back to
// the last clicked row.
const wasControlled = ref(
  props.value !== undefined || props.modelValue !== undefined,
)
watch(
  () => [props.value, props.modelValue],
  ([v, m]) => {
    if (v !== undefined || m !== undefined) wasControlled.value = true
  },
)
const isValueControlled = computed(() => wasControlled.value)
const internalValue = ref<string | undefined>(props.value ?? props.modelValue)
const value = computed(() =>
  isValueControlled.value
    ? props.value ?? props.modelValue
    : internalValue.value,
)

const selected = computed<SelectItem | null>(() => {
  if (value.value === undefined) return null
  const found = props.items.find(
    (it) => SelectConstants.getItemValue(it) === value.value,
  )
  return found ?? null
})

const defaultTriggerLabel = computed(() => {
  if (selected.value && 'label' in selected.value) {
    return (selected.value as { label: string }).label
  }
  return props.placeholder ?? ''
})

// When the trigger has no label text (no selection AND no placeholder),
// render it as an icon-only square so the chevron alone doesn't sit in a
// stretched-out button. Matches Button's `square` rule: width === height.
const isTriggerIconOnly = computed(() => !defaultTriggerLabel.value)

// ---------- search ----------
// `searchValue` lives on Select (not OptionList) so the keyboard handler
// and the rendered popover work off the SAME filtered list. Before this,
// Select walked indices on the raw `items` while OptionList re-filtered
// internally — Enter could select rows hidden by the search filter.
const searchValue = ref('')
const displayItems = computed(() =>
  props.searchable && props.searchFilters
    ? filterAndCollapseHeadlines(props.items, searchValue.value)
    : props.items,
)

// ---------- focused index ----------
// -1 means "no row focused" — visual focus ring + aria-activedescendant are
// suppressed until the user actually navigates with an arrow key.
const focusedIndex = ref(-1)
const selectableIndices = computed(() =>
  getSelectableIndices(displayItems.value),
)

watch(open, (isOpen) => {
  if (!isOpen) return
  // Open with no row focused. First arrow keypress lands focus (see onKeyDown).
  focusedIndex.value = -1
})

// Anything that shrinks the visible list — typing into search or the
// consumer swapping `items` (e.g., a header-tab change) — can leave
// `focusedIndex` past the end of `selectableIndices`, which makes
// `aria-activedescendant` resolve to an id ending in `undefined` and
// hides the focus ring. Reset to -1 whenever the displayed list changes.
watch(displayItems, () => {
  focusedIndex.value = -1
})

// ---------- click outside ----------
const wrapperRef = ref<HTMLElement | null>(null)
function onDocumentMouseDown(e: MouseEvent) {
  if (!open.value) return
  if (!wrapperRef.value) return
  if (e.target instanceof Node && wrapperRef.value.contains(e.target)) return
  setOpen(false)
}
onMounted(() => {
  document.addEventListener('mousedown', onDocumentMouseDown, true)
})
onBeforeUnmount(() => {
  document.removeEventListener('mousedown', onDocumentMouseDown, true)
})

// ---------- keyboard ----------
const triggerRef = ref<HTMLElement | null>(null)
function onKeyDown(e: KeyboardEvent) {
  if (props.disabled) return
  if (!open.value) {
    if (e.key === 'Enter' || e.key === ' ' || e.key === 'ArrowDown') {
      e.preventDefault()
      setOpen(true)
    }
    return
  }
  if (e.key === 'Escape') {
    e.preventDefault()
    setOpen(false)
    const btn = triggerRef.value?.querySelector(
      'button, [tabindex]',
    ) as HTMLElement | null
    btn?.focus()
    return
  }
  if (e.key === 'Tab') {
    setOpen(false)
    return
  }
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    const n = selectableIndices.value.length
    if (n === 0) {
      focusedIndex.value = -1
    } else if (focusedIndex.value === -1) {
      // First arrow press lands on the first option.
      focusedIndex.value = 0
    } else {
      focusedIndex.value = (focusedIndex.value + 1) % n
    }
    return
  }
  if (e.key === 'ArrowUp') {
    e.preventDefault()
    const n = selectableIndices.value.length
    if (n === 0) {
      focusedIndex.value = -1
    } else if (focusedIndex.value === -1) {
      // First arrow press from no-focus lands on the last option — wraps
      // symmetrically with ArrowDown-from-last.
      focusedIndex.value = n - 1
    } else {
      focusedIndex.value = (focusedIndex.value - 1 + n) % n
    }
    return
  }
  if (e.key === 'Enter' || e.key === ' ') {
    // No-op when nothing is focused yet — and crucially, do NOT
    // preventDefault. The wrapper @keydown also fires for keys typed
    // INTO the header search input (events bubble), so swallowing
    // Space here would block multi-word search queries.
    if (focusedIndex.value === -1) return
    const realIndex = selectableIndices.value[focusedIndex.value]
    if (realIndex === undefined) return
    // Both Enter and Space confirm the focused row. preventDefault
    // suppresses the native button-activation that would otherwise toggle
    // the popover closed without selecting.
    e.preventDefault()
    handleSelect(displayItems.value[realIndex])
  }
}

// ---------- selection ----------
function handleSelect(item: SelectItem) {
  const itemValue = SelectConstants.getItemValue(item)
  if (itemValue === undefined) return
  // Checkbox rows toggle: clicking an already-checked row unchecks it.
  // Default rows still use plain select semantics (re-click is a no-op).
  // Keep the popover open on checkbox toggle so multi-pick intent flows.
  const isCheckboxToggle = item.type === 'checkbox' && value.value === itemValue
  const nextValue = isCheckboxToggle ? undefined : itemValue
  // Uncontrolled consumers: track the selection internally. Controlled
  // consumers (v-model or `value`): the parent's prop drives the next
  // render; don't touch internalValue so a controlled clear (parent sets
  // `value`/`modelValue` to `undefined`) shows the placeholder instead
  // of falling back to the last clicked row.
  if (!isValueControlled.value) internalValue.value = nextValue
  emit('update:modelValue', nextValue)
  emit('change', nextValue, item)
  if (item.type !== 'checkbox') setOpen(false)
}

function toggle() {
  setOpen(!open.value)
}
function close() {
  setOpen(false)
}

const activeDescendantId = computed(() =>
  open.value && focusedIndex.value >= 0
    ? `${itemIdPrefix.value}-${selectableIndices.value[focusedIndex.value]}`
    : undefined,
)

const chevronClasses = computed(() => [
  SelectConstants.CssChevronClasses,
  open.value ? SelectConstants.CssChevronOpenClasses : '',
])
</script>

<template>
  <div
    ref="wrapperRef"
    :class="[SelectConstants.CssWrapperClasses]"
    @keydown="onKeyDown"
  >
    <div ref="triggerRef">
      <slot
        name="trigger"
        :open="open"
        :selected="selected"
        :toggle="toggle"
        :close="close"
      >
        <Button
          :variant="triggerVariant as never"
          :size="size"
          :square="isTriggerIconOnly"
          :disabled="disabled"
          type="button"
          aria-haspopup="listbox"
          :aria-expanded="open"
          :aria-controls="popoverId"
          :aria-activedescendant="activeDescendantId"
          :class="
            isTriggerIconOnly ? '' : SelectConstants.CssTriggerWidthClasses
          "
          @click="toggle"
        >
          <span
            v-if="isTriggerIconOnly"
            :class="SelectConstants.CssTriggerIconOnlyClasses"
          >
            <IconChevronDownSmall :class="chevronClasses" />
          </span>
          <span v-else :class="SelectConstants.CssTriggerContentClasses">
            <span class="truncate">{{ defaultTriggerLabel }}</span>
            <IconChevronDownSmall :class="chevronClasses" />
          </span>
        </Button>
      </slot>
    </div>

    <SelectOptionList
      v-if="open"
      :id="popoverId"
      :item-id-prefix="itemIdPrefix"
      :items="displayItems"
      :theme="theme"
      :size="size"
      :value="value"
      :header-title="headerTitle"
      :header-button="headerButton"
      :header-icon-left="headerIconLeft"
      :header-tag="headerTag"
      :header-icon-right="headerIconRight"
      :header-tabs="headerTabs"
      :header-active-tab="headerActiveTab"
      :searchable="searchable"
      :search-placeholder="searchPlaceholder"
      :search-value="searchValue"
      :footer-label="footerLabel"
      :footer-action="footerAction"
      :width="width"
      :min-width="minWidth"
      :max-width="maxWidth"
      :height="height"
      :max-height="maxHeight"
      :align="align"
      :focused-index="focusedIndex"
      :panel-class="popoverClass"
      @update:search-value="(v: string) => (searchValue = v)"
      @select="(it: SelectItem) => handleSelect(it)"
      @header-tab-change="(id: string) => emit('header-tab-change', id)"
    >
      <template v-if="$slots.footer" #footer>
        <slot name="footer" />
      </template>
    </SelectOptionList>
  </div>
</template>

// components/Select/react/Select.tsx
import * as React from 'react'
import clsx from 'clsx'
import Button from '@cypress-design/react-button'
import { IconChevronDownSmall } from '@cypress-design/react-icon'
import * as SelectConstants from '@cypress-design/constants-select'
import type {
  SelectItem,
  SelectAlignment,
  ButtonVariantLoose,
  SelectThemingProps,
  SelectHeaderProps,
  SelectSearchProps,
  SelectFooterProps,
  SelectSizingProps,
} from '@cypress-design/constants-select'
import SelectOptionList from './SelectOptionList'
import {
  filterAndCollapseHeadlines,
  getSelectableIndices,
} from './filter-items'

export interface SelectTriggerContext {
  open: boolean
  selected: SelectItem | null
  toggle: () => void
  close: () => void
}

// Composed from the shared prop groups in `constants-select` so the surface
// stays in sync with SelectOptionList / SelectOptionItem; only Select-only
// fields live in the body below.
export interface SelectProps
  extends SelectThemingProps,
    SelectHeaderProps,
    SelectSearchProps,
    SelectFooterProps,
    SelectSizingProps {
  align?: SelectAlignment
  triggerVariant?: ButtonVariantLoose

  items: SelectItem[]

  value?: string
  defaultValue?: string
  // `value` is `undefined` when the selection is cleared — that happens when
  // a checkbox row is re-clicked (toggle off). Consumers must handle both
  // cases.
  onChange?: (value: string | undefined, item: SelectItem) => void

  placeholder?: string
  disabled?: boolean

  onHeaderTabChange?: (id: string) => void

  // React-only: the footer slot accepts arbitrary ReactNode in addition to
  // the structured footerLabel / footerAction props from SelectFooterProps.
  footer?: React.ReactNode

  // Open state
  defaultOpen?: boolean
  open?: boolean
  onOpenChange?: (open: boolean) => void

  // Escape hatches
  trigger?: React.ReactNode | ((ctx: SelectTriggerContext) => React.ReactNode)
  className?: string
  popoverClassName?: string
  id?: string
}

let uidCounter = 0
const useUid = () => {
  const [uid] = React.useState(() => `cy-select-${++uidCounter}`)
  return uid
}

export const Select: React.FC<SelectProps> = ({
  theme = SelectConstants.DefaultTheme,
  size = SelectConstants.DefaultSize,
  align = SelectConstants.DefaultAlignment,
  triggerVariant = SelectConstants.DefaultTriggerVariant,
  items,
  value: valueProp,
  defaultValue,
  onChange,
  placeholder,
  disabled = false,
  headerTitle,
  headerButton,
  headerIconLeft,
  headerTag,
  headerIconRight,
  headerTabs,
  headerActiveTab,
  onHeaderTabChange,
  searchable = false,
  searchPlaceholder,
  // Matches the Vue default so that callers passing `searchable` without
  // also passing `searchFilters` still get the filter behavior the
  // instructions document (`searchFilters` defaults to `true`).
  searchFilters = true,
  footer,
  footerLabel,
  footerAction,
  width,
  minWidth,
  maxWidth,
  height,
  maxHeight,
  defaultOpen = false,
  open: openProp,
  onOpenChange,
  trigger,
  className,
  popoverClassName,
  id,
}) => {
  const uid = useUid()
  const popoverId = id ? `${id}-popover` : `${uid}-popover`
  const itemIdPrefix = id ? `${id}-opt` : `${uid}-opt`

  // ---------- Open state (controlled / uncontrolled) ----------
  const isOpenControlled = openProp !== undefined
  const [internalOpen, setInternalOpen] = React.useState(defaultOpen)
  const open = isOpenControlled ? openProp : internalOpen
  const setOpen = (next: boolean) => {
    if (!isOpenControlled) setInternalOpen(next)
    onOpenChange?.(next)
  }

  // ---------- Selected value ----------
  // Sticky-toward-controlled: once we ever see a defined `value` prop the
  // component is "controlled" and stays that way for the rest of its life.
  // This is the only discriminator that handles every common pattern:
  //   - Pure uncontrolled (no `value` ever): stays uncontrolled, falls
  //     back to `internalValue`.
  //   - Pure controlled (initial defined): controlled from render 1, the
  //     parent's `value` always wins.
  //   - Lazy controlled (`useState<string|undefined>(undefined)` + `value`):
  //     uncontrolled until the parent first sets a defined value, then
  //     locks into controlled.
  //   - Controlled clear (parent sets `value` to `undefined` after it was
  //     defined): stays controlled — trigger shows the placeholder
  //     instead of falling back to a stale `internalValue`.
  //   - Checkbox toggle-off (component emits `undefined` via onChange):
  //     same as controlled clear if the parent reflects it; the prop
  //     wins and the trigger clears cleanly.
  const wasControlledRef = React.useRef(false)
  if (valueProp !== undefined) wasControlledRef.current = true
  const isValueControlled = wasControlledRef.current
  const [internalValue, setInternalValue] = React.useState<string | undefined>(
    defaultValue,
  )
  const value = isValueControlled ? valueProp : internalValue

  const selected = React.useMemo<SelectItem | null>(() => {
    if (value === undefined) return null
    const found = items.find((it) => SelectConstants.getItemValue(it) === value)
    return found ?? null
  }, [items, value])

  // ---------- Focused index (within filtered selectables) ----------
  // -1 means "no row focused" — the visual focus ring + aria-activedescendant
  // are suppressed until the user actually navigates with an arrow key.
  const [focusedIndex, setFocusedIndex] = React.useState(-1)
  // `searchValue` lives here (not in OptionList) so the keyboard handler
  // and the rendered popover work off the same filtered list. Before this,
  // Select walked indices on the raw `items` while OptionList re-filtered
  // internally — Enter could select rows hidden by the search filter and
  // `aria-activedescendant` pointed at non-rendered ids.
  const [searchValue, setSearchValue] = React.useState('')
  const displayItems = React.useMemo(
    () =>
      searchable && searchFilters
        ? filterAndCollapseHeadlines(items, searchValue)
        : items,
    [items, searchable, searchFilters, searchValue],
  )
  const selectableIndices = React.useMemo(
    () => getSelectableIndices(displayItems),
    [displayItems],
  )

  // Open the popover with no focused row. The first arrow keypress lands
  // focus on the first option (or the last, on ArrowUp) — see onKeyDown.
  React.useEffect(() => {
    if (!open) return
    setFocusedIndex(-1)
  }, [open])

  // Anything that shrinks the visible list — typing into search or the
  // consumer swapping `items` (e.g., a header-tab change) — can leave
  // `focusedIndex` past the end of `selectableIndices`, which makes
  // `aria-activedescendant` resolve to an id ending in `undefined` and
  // hides the focus ring. Reset to -1 whenever the displayed list changes.
  React.useEffect(() => {
    setFocusedIndex(-1)
  }, [displayItems])

  // ---------- Click outside ----------
  const wrapperRef = React.useRef<HTMLDivElement | null>(null)
  React.useEffect(() => {
    if (!open) return
    const handler = (e: MouseEvent) => {
      if (!wrapperRef.current) return
      if (e.target instanceof Node && wrapperRef.current.contains(e.target)) {
        return
      }
      setOpen(false)
    }
    document.addEventListener('mousedown', handler, true)
    return () => document.removeEventListener('mousedown', handler, true)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  // ---------- Keyboard ----------
  const triggerRef = React.useRef<HTMLDivElement | null>(null)
  const onKeyDown = (e: React.KeyboardEvent) => {
    if (disabled) return
    if (!open) {
      if (e.key === 'Enter' || e.key === ' ' || e.key === 'ArrowDown') {
        e.preventDefault()
        setOpen(true)
      }
      return
    }
    if (e.key === 'Escape') {
      e.preventDefault()
      setOpen(false)
      ;(
        triggerRef.current?.querySelector(
          'button, [tabindex]',
        ) as HTMLElement | null
      )?.focus()
      return
    }
    if (e.key === 'Tab') {
      setOpen(false)
      return
    }
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setFocusedIndex((i) => {
        const n = selectableIndices.length
        if (n === 0) return -1
        // First arrow press (i === -1) lands on the first option.
        if (i === -1) return 0
        return (i + 1) % n
      })
      return
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault()
      setFocusedIndex((i) => {
        const n = selectableIndices.length
        if (n === 0) return -1
        // First arrow press (i === -1) lands on the last option — wraps
        // symmetrically with ArrowDown-from-last.
        if (i === -1) return n - 1
        return (i - 1 + n) % n
      })
      return
    }
    if (e.key === 'Enter' || e.key === ' ') {
      // No-op when nothing is focused yet — and crucially, do NOT
      // preventDefault. The wrapper onKeyDown also fires for keys typed
      // INTO the header search input (events bubble), so swallowing
      // Space here would block multi-word search queries.
      if (focusedIndex === -1) return
      const realIndex = selectableIndices[focusedIndex]
      if (realIndex === undefined) return
      // Both Enter and Space confirm the focused row. preventDefault
      // suppresses the native button-activation that would otherwise toggle
      // the popover closed without selecting.
      e.preventDefault()
      const item = displayItems[realIndex]
      handleSelect(item)
    }
  }

  // ---------- Selection ----------
  const handleSelect = (item: SelectItem) => {
    const itemValue = SelectConstants.getItemValue(item)
    if (itemValue === undefined) return
    // Checkbox rows toggle: clicking an already-checked row unchecks it.
    // Default rows still use plain select semantics (re-click is a no-op).
    // We also keep the popover open on checkbox toggle since the user is
    // likely picking multiple from a multi-select intent.
    const isCheckboxToggle = item.type === 'checkbox' && value === itemValue
    const nextValue = isCheckboxToggle ? undefined : itemValue
    // Uncontrolled consumers: track the selection internally. Controlled
    // consumers: the parent's prop drives the next render; don't touch
    // internalValue (otherwise a parent that clears `value` to `undefined`
    // would still see the cleared trigger fall back to the last clicked
    // row — exactly the "stale label" bug Cursor caught).
    if (!isValueControlled) setInternalValue(nextValue)
    onChange?.(nextValue, item)
    if (item.type !== 'checkbox') setOpen(false)
  }

  // ---------- Trigger rendering ----------
  const toggle = () => setOpen(!open)
  const close = () => setOpen(false)
  const triggerCtx: SelectTriggerContext = { open, selected, toggle, close }

  const defaultTriggerLabel =
    selected && 'label' in selected ? selected.label : placeholder ?? ''
  // When the trigger has no label text (no selection AND no placeholder),
  // render it as an icon-only square so the chevron alone doesn't sit in a
  // stretched-out button.
  const isTriggerIconOnly = !defaultTriggerLabel

  const triggerNode =
    typeof trigger === 'function' ? (
      trigger(triggerCtx)
    ) : trigger !== undefined ? (
      trigger
    ) : (
      <Button
        variant={triggerVariant as never}
        size={size}
        square={isTriggerIconOnly}
        disabled={disabled}
        type="button"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-controls={popoverId}
        aria-activedescendant={
          open && focusedIndex >= 0
            ? `${itemIdPrefix}-${selectableIndices[focusedIndex]}`
            : undefined
        }
        onClick={toggle}
        className={
          isTriggerIconOnly ? undefined : SelectConstants.CssTriggerWidthClasses
        }
      >
        <span
          className={
            isTriggerIconOnly
              ? SelectConstants.CssTriggerIconOnlyClasses
              : SelectConstants.CssTriggerContentClasses
          }
        >
          {!isTriggerIconOnly && (
            <span className="truncate">{defaultTriggerLabel}</span>
          )}
          <IconChevronDownSmall
            className={clsx(
              SelectConstants.CssChevronClasses,
              open && SelectConstants.CssChevronOpenClasses,
            )}
          />
        </span>
      </Button>
    )

  return (
    <div
      ref={wrapperRef}
      className={clsx(SelectConstants.CssWrapperClasses, className)}
      onKeyDown={onKeyDown}
    >
      <div ref={triggerRef}>{triggerNode}</div>
      {open && (
        <SelectOptionList
          id={popoverId}
          itemIdPrefix={itemIdPrefix}
          items={displayItems}
          theme={theme}
          size={size}
          value={value}
          onSelect={handleSelect}
          headerTitle={headerTitle}
          headerButton={headerButton}
          headerIconLeft={headerIconLeft}
          headerTag={headerTag}
          headerIconRight={headerIconRight}
          headerTabs={headerTabs}
          headerActiveTab={headerActiveTab}
          onHeaderTabChange={onHeaderTabChange}
          searchable={searchable}
          searchPlaceholder={searchPlaceholder}
          searchValue={searchValue}
          onSearchValueChange={setSearchValue}
          footer={footer}
          footerLabel={footerLabel}
          footerAction={footerAction}
          width={width}
          minWidth={minWidth}
          maxWidth={maxWidth}
          height={height}
          maxHeight={maxHeight}
          align={align}
          focusedIndex={focusedIndex}
          className={popoverClassName}
        />
      )}
    </div>
  )
}

export default Select
