// components/Modal/react/Modal.tsx
import * as React from 'react'
import { createPortal } from 'react-dom'
import clsx from 'clsx'
import {
  IconActionQuestionMarkCircle,
  IconActionDelete,
} from '@cypress-design/react-icon'
import {
  ClassCloseButton,
  ClassContent,
  ClassHelpLink,
  ClassHelpLinkDash,
  ClassModal,
  ClassModalFullscreenDimensions,
  ClassModalStandardDimensions,
  ClassTitle,
  ClassTitleBox,
  disableBodyScroll,
  freeBodyScroll,
} from '@cypress-design/constants-modal'

export interface ModalProps {
  title?: string
  helpLink?: string
  helpLinkLabel?: string
  children?: React.ReactNode
  show?: boolean
  onClose?: () => void
  fullscreen?: boolean
  className?: string
  closeIcon?: React.ReactNode
}

export const Modal: React.FC<ModalProps> = ({
  show = false,
  title,
  helpLink,
  helpLinkLabel = 'Need help',
  onClose,
  children,
  fullscreen = false,
  className,
  closeIcon,
}) => {
  const dialogRef = React.useRef<HTMLDialogElement>(null)

  React.useEffect(() => {
    if (show) {
      disableBodyScroll()
      dialogRef.current?.showModal()
    } else {
      dialogRef.current?.close()
      freeBodyScroll()
    }
  }, [show, onClose])

  React.useEffect(
    () => () => {
      freeBodyScroll()
    },
    [],
  )

  const closeOnClickBackdrop = React.useCallback<
    React.MouseEventHandler<HTMLDialogElement>
  >(
    (event) => {
      const rect = dialogRef.current?.getBoundingClientRect()
      if (!rect) return
      const isInDialog =
        rect.top <= event.clientY &&
        event.clientY <= rect.top + rect.height &&
        rect.left <= event.clientX &&
        event.clientX <= rect.left + rect.width
      if (!isInDialog) {
        onClose?.()
      }
    },
    [onClose],
  )

  // Escape fires `cancel` on the native dialog. Stop the browser closing it
  // behind our back and let the parent close it through `onClose`.
  const closeOnCancel = React.useCallback<
    React.ReactEventHandler<HTMLDialogElement>
  >(
    (event) => {
      event.preventDefault()
      onClose?.()
    },
    [onClose],
  )

  return (
    show &&
    createPortal(
      <dialog
        ref={dialogRef}
        className={clsx(
          show ? ClassModal : null,
          fullscreen
            ? ClassModalFullscreenDimensions
            : ClassModalStandardDimensions,
          className,
        )}
        onClick={closeOnClickBackdrop}
        onCancel={closeOnCancel}
      >
        <div className={ClassTitleBox}>
          <div id="cy_modal_label" className={ClassTitle}>
            {title}
          </div>
          {helpLink ? <div className={ClassHelpLinkDash} /> : null}
          {helpLink ? (
            <a
              href={helpLink}
              className={ClassHelpLink}
              target="_blank"
              rel="noopener noreferrer"
            >
              {helpLinkLabel}
              <IconActionQuestionMarkCircle
                className="ml-[4px]"
                stroke-color="indigo-500"
                fill-color="indigo-100"
              />
            </a>
          ) : null}

          <div className="grow" />
          <button
            aria-label="Close"
            className={`${ClassCloseButton} group`}
            onClick={() => onClose?.()}
          >
            {closeIcon ?? (
              <IconActionDelete
                className="children:transition-all"
                stroke-color="gray-400"
                hover-stroke-color="gray-700"
                interactiveColorsOnGroup
              />
            )}
          </button>
        </div>
        <div className={ClassContent}>{children}</div>
      </dialog>,
      document.body,
    )
  )
}

export default Modal

// components/Modal/vue/Modal.vue
<script lang="ts" setup>
import { onMounted, onUnmounted, ref, watch } from 'vue'
import {
  ClassModal,
  ClassModalFullscreenDimensions,
  ClassModalStandardDimensions,
  ClassTitleBox,
  ClassTitle,
  ClassHelpLinkDash,
  ClassHelpLink,
  ClassCloseButton,
  ClassContent,
  disableBodyScroll,
  freeBodyScroll,
} from '@cypress-design/constants-modal'
import {
  IconActionDelete,
  IconActionQuestionMarkCircle,
} from '@cypress-design/vue-icon'

const internalShow = ref(false)

const emit = defineEmits<{
  (event: 'close'): void
  (event: 'update:show', value: boolean): void
}>()

const props = withDefaults(
  defineProps<{
    title?: string
    show?: boolean
    helpLink?: string
    helpLinkLabel?: string
    fullscreen?: boolean
  }>(),
  {
    helpLinkLabel: 'Need help',
  },
)

defineSlots<{
  default?: () => unknown
  closeIcon?: () => unknown
}>()

const $dialog = ref<HTMLDialogElement>()

watch(
  () => props.show,
  (val) => {
    internalShow.value = val
  },
  { immediate: true },
)

onMounted(() => {
  if (!document.querySelector('#modal-target')) {
    const modalTarget = document.createElement('div')
    modalTarget.id = 'modal-target'
    document.body.appendChild(modalTarget)
  }
})

watch(internalShow, (val) => {
  if (val) {
    disableBodyScroll()
    $dialog.value?.showModal()
  } else {
    $dialog.value?.close()
    freeBodyScroll()
  }

  emit('update:show', val)
  if (!val) {
    emit('close')
  }
})

onUnmounted(() => {
  freeBodyScroll()
})

function closeOnClickBackdrop(event: MouseEvent) {
  var rect = $dialog.value?.getBoundingClientRect()
  if (!rect) return
  var isInDialog =
    rect.top <= event.clientY &&
    event.clientY <= rect.top + rect.height &&
    rect.left <= event.clientX &&
    event.clientX <= rect.left + rect.width
  if (!isInDialog) {
    internalShow.value = false
  }
}

// Escape fires `cancel` on the native dialog. Stop the browser closing it
// behind our back and close through the same path as the close button.
function closeOnCancel(event: Event) {
  event.preventDefault()
  internalShow.value = false
}
</script>

<template>
  <dialog
    ref="$dialog"
    :class="[
      internalShow ? ClassModal : null,
      fullscreen
        ? ClassModalFullscreenDimensions
        : ClassModalStandardDimensions,
    ]"
    @click="closeOnClickBackdrop"
    @cancel="closeOnCancel"
  >
    <div :class="ClassTitleBox">
      <div id="cy_modal_label" :class="ClassTitle">
        {{ title }}
      </div>
      <div v-if="helpLink" :class="ClassHelpLinkDash" />
      <a
        v-if="helpLink"
        :href="helpLink"
        :class="ClassHelpLink"
        target="_blank"
        rel="noopener noreferrer"
      >
        {{ helpLinkLabel }}
        <IconActionQuestionMarkCircle
          class="ml-[4px]"
          stroke-color="indigo-500"
          fill-color="indigo-100"
        />
      </a>
      <div class="grow" />
      <button
        aria-label="Close"
        :class="[ClassCloseButton, 'group']"
        @click="internalShow = false"
      >
        <slot name="closeIcon">
          <IconActionDelete
            class="children:transition-all"
            stroke-color="gray-400"
            hover-stroke-color="gray-700"
            interactive-colors-on-group
          />
        </slot>
      </button>
    </div>
    <div :class="ClassContent">
      <slot />
    </div>
  </dialog>
</template>
