// components/Select/react/SelectOptionItem.tsx
import * as React from 'react'
import clsx from 'clsx'
import Checkbox from '@cypress-design/react-checkbox'
import Button from '@cypress-design/react-button'
import Tag from '@cypress-design/react-tag'
import type { ButtonVariants } from '@cypress-design/constants-button'
import type { OpenIconProps } from '@cypress-design/icon-registry'
import * as SelectConstants from '@cypress-design/constants-select'
import type {
  SelectItem,
  SelectTheme,
  SelectSize,
} from '@cypress-design/constants-select'

// Consumer-passed icon component: any cypress-design Icon (or a compatible
// component that accepts the same props minus the `name` discriminator).
// `className` is appended because `renderIcon` and the default-row JSX
// pass it for state-aware coloring; cypress-design Icons accept it via
// their RootIconProps surface but the public `OpenIconProps` doesn't
// declare it.
type IconComponent = React.ComponentType<
  Omit<OpenIconProps, 'name'> & { className?: string }
>

export interface SelectOptionItemProps {
  item: SelectItem
  theme: SelectTheme
  size: SelectSize
  selected: boolean
  focused: boolean
  id?: string
  onSelect: (item: SelectItem) => void
}

function renderIcon(
  Icon: unknown,
  className: string,
  size: '16' | '24' = '16',
): React.ReactNode {
  if (!Icon) return null
  if (React.isValidElement(Icon)) {
    return <span className={className}>{Icon}</span>
  }
  if (typeof Icon === 'function') {
    const Component = Icon as IconComponent
    return (
      <Component
        size={size}
        interactiveColorsOnGroup={true}
        className={className}
      />
    )
  }
  return <span className="shrink-0">{Icon as React.ReactNode}</span>
}

export const SelectOptionItem: React.FC<SelectOptionItemProps> = ({
  item,
  theme,
  size,
  selected,
  focused,
  id,
  onSelect,
}) => {
  // Non-row content types are handled before the row chrome is rendered.
  if (item.type === 'headline') {
    return (
      <div
        id={id}
        role="presentation"
        className={clsx(
          SelectConstants.CssOptionHeadlineClasses[theme],
          SelectConstants.CssOptionItemPaddingClasses[size],
        )}
      >
        {item.label}
      </div>
    )
  }

  if (item.type === 'divider') {
    return (
      <div role="presentation" aria-hidden="true">
        <div className={SelectConstants.CssOptionDividerClasses[theme]} />
      </div>
    )
  }

  if (item.type === 'button') {
    // Theme-aware default variant — `white` on light reads as a soft outline
    // pill; on dark we use `outline-dark` so it doesn't sit as a stark white
    // pill against the gray-1000 panel. Mirrors the header back-button rule.
    const buttonVariant =
      item.variant ?? (theme === 'dark' ? 'outline-dark' : 'white')
    // Scale the button height with the row size so the action button doesn't
    // look puny in a `size=40` panel.
    const buttonSize = size === '40' ? '32' : '24'
    return (
      // The wrapper stays purely presentational — the pill Button IS the
      // interactive control, so the pill is the sole click target
      // (preserved from the original behavior; the row's negative space
      // does not trigger the action).
      // The inner Button carries `role="option"` so the listbox sees a
      // valid child (`aria-required-children`), and `tabindex="-1"` so
      // the trigger's `aria-activedescendant` owns focus rather than
      // native tab landing on the pill.
      <div
        role="presentation"
        className={clsx(
          SelectConstants.CssButtonRowClasses,
          SelectConstants.CssOptionItemHeightClasses[size],
          SelectConstants.CssOptionItemPaddingClasses[size],
          SelectConstants.CssButtonRowFocusClasses[theme],
        )}
      >
        <Button
          variant={buttonVariant as ButtonVariants}
          size={buttonSize}
          id={id}
          role="option"
          tabIndex={-1}
          data-focused={focused || undefined}
          onClick={(e) => {
            e.stopPropagation()
            item.onClick()
          }}
        >
          {/* Route through renderIcon so the button row accepts the same
              two shapes (component reference OR ReactElement) as
              default-row iconLeft. Rendering the raw value as JSX
              (`<Icon />`) throws when the consumer hands us a
              `<MyIcon />` element instead of `MyIcon`. */}
          {renderIcon(item.iconLeft, 'shrink-0')}
          {item.label}
        </Button>
      </div>
    )
  }

  // From here on, the row uses the shared chrome (state-bearing div).
  const disabled =
    (item.type === 'default' ||
      item.type === undefined ||
      item.type === 'checkbox' ||
      item.type === 'user') &&
    item.disabled === true

  const itemClasses = clsx(
    SelectConstants.CssOptionItemBaseClasses,
    SelectConstants.CssOptionItemClasses[`${theme}-default`],
    SelectConstants.CssOptionItemHeightClasses[size],
    SelectConstants.CssOptionItemPaddingClasses[size],
    SelectConstants.CssOptionItemGapClasses,
  )

  const iconColorClass = SelectConstants.CssOptionItemIconColorClasses[theme]

  const handleClick = (e: React.MouseEvent) => {
    if (disabled) return
    e.stopPropagation()
    onSelect(item)
  }

  // Custom row
  if (item.type === 'custom') {
    const isSelectable = typeof item.value === 'string'
    return (
      <div
        id={id}
        role={isSelectable ? 'option' : 'presentation'}
        aria-selected={isSelectable ? selected : undefined}
        aria-disabled={disabled || undefined}
        data-selected={selected || undefined}
        data-focused={focused || undefined}
        className={itemClasses}
        onClick={isSelectable ? handleClick : undefined}
        onMouseDown={(e) => e.preventDefault()}
      >
        {item.render({ selected }) as React.ReactNode}
      </div>
    )
  }

  // Checkbox row
  if (item.type === 'checkbox') {
    return (
      <div
        id={id}
        role="option"
        aria-selected={selected}
        aria-disabled={disabled || undefined}
        data-selected={selected || undefined}
        data-focused={focused || undefined}
        className={clsx(itemClasses, SelectConstants.CssCheckboxRowClasses)}
        onClick={handleClick}
        onMouseDown={(e) => e.preventDefault()}
      >
        <span
          className={SelectConstants.CssCheckboxRowCheckboxWrapperClasses}
          // The row itself owns interactivity (role="option", aria-selected,
          // click handler, keyboard nav). The visual checkbox is a
          // decorative affordance — hide it from assistive tech so axe's
          // `label` / `nested-interactive` rules don't fire.
          aria-hidden="true"
        >
          {/* The Checkbox initializes `localChecked` from `props.checked`
             via useState (uncontrolled) and never syncs back from the
             prop. Keying by `selected` forces a remount whenever the
             row toggles so the visual stays in sync with our externally-
             managed value. `hideInput` removes the real <input> from
             layout via display:none — axe's `nested-interactive` rule
             flags a focusable input inside a clickable row even when
             the input is tabIndex=-1 + aria-hidden, so we take it out
             of the DOM's interactive path entirely. */}
          <Checkbox
            key={selected ? 'on' : 'off'}
            checked={selected}
            disabled={disabled}
            onChange={() => undefined}
            inputTabIndex={-1}
            hideInput
          />
        </span>
        <div className={SelectConstants.CssCheckboxRowStackClasses}>
          <span className={SelectConstants.CssCheckboxRowLabelClasses[size]}>
            {item.label}
          </span>
          {item.subText && (
            <span
              className={SelectConstants.CssOptionItemSubTextClasses[theme]}
            >
              {item.subText}
            </span>
          )}
        </div>
      </div>
    )
  }

  // User row
  if (item.type === 'user') {
    return (
      <div
        id={id}
        role="option"
        aria-selected={selected}
        aria-disabled={disabled || undefined}
        data-selected={selected || undefined}
        data-focused={focused || undefined}
        className={itemClasses}
        onClick={handleClick}
        onMouseDown={(e) => e.preventDefault()}
      >
        {renderIcon(item.iconLeft, iconColorClass, '24')}
        <div className={SelectConstants.CssUserRowStackClasses}>
          <span className={SelectConstants.CssUserRowLabelClasses[size]}>
            {item.label}
          </span>
          {item.secondary && (
            <span className={SelectConstants.CssUserRowSecondaryClasses[theme]}>
              {item.secondary}
            </span>
          )}
        </div>
      </div>
    )
  }

  // Default row (type === 'default' or undefined)
  return (
    <div
      id={id}
      role="option"
      aria-selected={selected}
      aria-disabled={disabled || undefined}
      data-selected={selected || undefined}
      data-focused={focused || undefined}
      className={itemClasses}
      onClick={handleClick}
      onMouseDown={(e) => e.preventDefault()}
    >
      {renderIcon(item.iconLeft, iconColorClass)}
      <span className={SelectConstants.CssOptionItemLabelClasses}>
        {item.label}
      </span>
      {item.tag && (
        <Tag size="16" color="gray" dark={theme === 'dark'}>
          {item.tag}
        </Tag>
      )}
      {/* iconRight uses `ml-auto` so it hugs the row's right edge; reuses
          the same state-aware icon color classes as iconLeft. */}
      {item.iconRight
        ? renderIcon(item.iconRight, clsx('ml-auto', iconColorClass))
        : null}
      {item.slotRight !== undefined && (
        <span className="ml-auto shrink-0">
          {item.slotRight as React.ReactNode}
        </span>
      )}
    </div>
  )
}

export default SelectOptionItem

// components/Select/vue/_SelectOptionItem.vue
<script lang="ts" setup>
import { computed, defineComponent, type PropType } from 'vue'
import Checkbox from '@cypress-design/vue-checkbox'
import Button from '@cypress-design/vue-button'
import Tag from '@cypress-design/vue-tag'
import type { ButtonVariants } from '@cypress-design/constants-button'
import * as SelectConstants from '@cypress-design/constants-select'
import type {
  SelectItem,
  SelectTheme,
  SelectSize,
} from '@cypress-design/constants-select'

// Vue's `<component :is>` expects a component definition, not arbitrary
// render output (VNodes, strings, fragments). Wrapping the consumer's
// `render` function in a minimal functional component lets us render
// whatever it returns — h() output, strings, fragments, or null.
const CustomRender = defineComponent({
  props: {
    render: {
      type: Function as PropType<(ctx: { selected: boolean }) => unknown>,
      required: true,
    },
    selected: { type: Boolean, required: true },
  },
  setup(props) {
    return () => props.render({ selected: props.selected })
  },
})

// Same trick for `slotRight` on default rows. `<component :is>` only works
// when the value is a component definition; with this helper Vue happily
// renders VNodes, strings, fragments, or anything the consumer hands in.
const NodeRender = defineComponent({
  props: { node: { required: true } },
  setup(props) {
    return () => (typeof props.node === 'function' ? props.node() : props.node)
  },
})

const props = defineProps<{
  item: SelectItem
  theme: SelectTheme
  size: SelectSize
  selected: boolean
  focused: boolean
  id?: string
}>()

const emit = defineEmits<{
  (e: 'select', item: SelectItem): void
}>()

const itemClasses = computed(() => [
  SelectConstants.CssOptionItemBaseClasses,
  SelectConstants.CssOptionItemClasses[`${props.theme}-default`],
  SelectConstants.CssOptionItemHeightClasses[props.size],
  SelectConstants.CssOptionItemPaddingClasses[props.size],
  SelectConstants.CssOptionItemGapClasses,
])

const iconColorClass = computed(
  () => SelectConstants.CssOptionItemIconColorClasses[props.theme],
)

const isDisabled = computed(() => {
  const t = props.item.type
  if (t === 'default' || t === undefined || t === 'checkbox' || t === 'user') {
    return (props.item as { disabled?: boolean }).disabled === true
  }
  return false
})

const isCustomSelectable = computed(
  () =>
    props.item.type === 'custom' &&
    typeof (props.item as { value?: string }).value === 'string',
)

function onClick(e: MouseEvent) {
  if (isDisabled.value) return
  e.stopPropagation()
  emit('select', props.item)
}

function onMouseDown(e: MouseEvent) {
  e.preventDefault()
}
</script>

<template>
  <!-- headline (non-interactive) -->
  <div
    v-if="item.type === 'headline'"
    :id="id"
    role="presentation"
    :class="[
      SelectConstants.CssOptionHeadlineClasses[theme],
      SelectConstants.CssOptionItemPaddingClasses[size],
    ]"
  >
    {{ item.label }}
  </div>

  <!-- divider -->
  <div
    v-else-if="item.type === 'divider'"
    role="presentation"
    aria-hidden="true"
  >
    <div :class="SelectConstants.CssOptionDividerClasses[theme]" />
  </div>

  <!-- button row (action). Theme-aware default variant: `white` on light /
       `outline-dark` on dark so the in-list action button doesn't sit as a
       stark white pill against the gray-1000 panel.
       Wrapper stays purely presentational — the pill Button IS the
       interactive control, so the pill is the sole click target. The
       inner Button carries `role="option"` so the listbox sees a valid
       child (aria-required-children), and `tabindex="-1"` so the
       trigger's aria-activedescendant owns focus. -->
  <div
    v-else-if="item.type === 'button'"
    role="presentation"
    :class="[
      SelectConstants.CssButtonRowClasses,
      SelectConstants.CssOptionItemHeightClasses[size],
      SelectConstants.CssOptionItemPaddingClasses[size],
      SelectConstants.CssButtonRowFocusClasses[theme],
    ]"
  >
    <Button
      :id="id"
      role="option"
      :tabindex="-1"
      :data-focused="focused || undefined"
      :variant="
        (item.variant as ButtonVariants) ??
        (theme === 'dark' ? 'outline-dark' : 'white')
      "
      :size="size === '40' ? '32' : '24'"
      @click.stop="item.onClick()"
    >
      <component
        :is="item.iconLeft"
        v-if="item.iconLeft"
        size="16"
        :interactive-colors-on-group="true"
      />
      {{ item.label }}
    </Button>
  </div>

  <!-- custom row -->
  <div
    v-else-if="item.type === 'custom'"
    :id="id"
    :role="isCustomSelectable ? 'option' : 'presentation'"
    :aria-selected="isCustomSelectable ? selected : undefined"
    :data-selected="selected || undefined"
    :data-focused="focused || undefined"
    :class="itemClasses"
    @click="isCustomSelectable ? onClick($event) : undefined"
    @mousedown="onMouseDown"
  >
    <CustomRender :render="item.render" :selected="selected" />
  </div>

  <!-- checkbox row -->
  <div
    v-else-if="item.type === 'checkbox'"
    :id="id"
    role="option"
    :aria-selected="selected"
    :aria-disabled="isDisabled || undefined"
    :data-selected="selected || undefined"
    :data-focused="focused || undefined"
    :class="[itemClasses, SelectConstants.CssCheckboxRowClasses]"
    @click="onClick"
    @mousedown="onMouseDown"
  >
    <!-- The row itself owns interactivity (role="option", aria-selected,
         click handler, keyboard nav). The visual checkbox is a decorative
         affordance — hide it from assistive tech so axe's `label` /
         `nested-interactive` rules don't fire. -->
    <span
      :class="SelectConstants.CssCheckboxRowCheckboxWrapperClasses"
      aria-hidden="true"
    >
      <!-- The Checkbox component owns its own `localChecked` state and
           doesn't watch the `:checked` prop for changes. Keying it on
           `selected` forces a remount whenever the row toggles, so the
           visual stays in sync with the externally-managed value.
           `hide-input` removes the real <input> from layout via
           display:none — axe's `nested-interactive` rule flags a
           focusable input inside a clickable row even when the input is
           tabindex=-1 + aria-hidden, so we take it out of the DOM's
           interactive path entirely. -->
      <Checkbox
        :key="selected ? 'on' : 'off'"
        :checked="selected"
        :disabled="isDisabled"
        :input-tab-index="-1"
        :hide-input="true"
        @change="() => undefined"
      />
    </span>
    <div :class="SelectConstants.CssCheckboxRowStackClasses">
      <span :class="SelectConstants.CssCheckboxRowLabelClasses[size]">
        {{ item.label }}
      </span>
      <span
        v-if="item.subText"
        :class="SelectConstants.CssOptionItemSubTextClasses[theme]"
      >
        {{ item.subText }}
      </span>
    </div>
  </div>

  <!-- user row -->
  <div
    v-else-if="item.type === 'user'"
    :id="id"
    role="option"
    :aria-selected="selected"
    :aria-disabled="isDisabled || undefined"
    :data-selected="selected || undefined"
    :data-focused="focused || undefined"
    :class="itemClasses"
    @click="onClick"
    @mousedown="onMouseDown"
  >
    <component
      :is="item.iconLeft"
      v-if="item.iconLeft"
      size="24"
      :interactive-colors-on-group="true"
      :class="iconColorClass"
    />
    <div :class="SelectConstants.CssUserRowStackClasses">
      <span :class="SelectConstants.CssUserRowLabelClasses[size]">
        {{ item.label }}
      </span>
      <span
        v-if="item.secondary"
        :class="SelectConstants.CssUserRowSecondaryClasses[theme]"
      >
        {{ item.secondary }}
      </span>
    </div>
  </div>

  <!-- default row (type === 'default' or undefined) -->
  <div
    v-else
    :id="id"
    role="option"
    :aria-selected="selected"
    :aria-disabled="isDisabled || undefined"
    :data-selected="selected || undefined"
    :data-focused="focused || undefined"
    :class="itemClasses"
    @click="onClick"
    @mousedown="onMouseDown"
  >
    <component
      :is="item.iconLeft"
      v-if="item.iconLeft"
      size="16"
      :interactive-colors-on-group="true"
      :class="iconColorClass"
    />
    <span :class="SelectConstants.CssOptionItemLabelClasses">
      {{ item.label }}
    </span>
    <Tag v-if="item.tag" size="16" color="gray" :dark="theme === 'dark'">
      {{ item.tag }}
    </Tag>
    <!-- iconRight: hugs the right edge via `ml-auto`, picks up the same
         state-aware coloring as iconLeft. -->
    <component
      :is="item.iconRight"
      v-if="item.iconRight"
      size="16"
      :interactive-colors-on-group="true"
      :class="['ml-auto', iconColorClass]"
    />
    <span v-if="item.slotRight" class="ml-auto shrink-0">
      <NodeRender :node="item.slotRight" />
    </span>
  </div>
</template>
