// components/Select/react/SelectOptionList.tsx
import * as React from 'react'
import clsx from 'clsx'
import Tabs from '@cypress-design/react-tabs'
import Textbox from '@cypress-design/react-textbox'
import Button from '@cypress-design/react-button'
import Tag from '@cypress-design/react-tag'
import {
  IconObjectMagnifyingGlass,
  IconActionInfoOutline,
} from '@cypress-design/react-icon'
import type { OpenIconProps } from '@cypress-design/icon-registry'
import type { Tab } from '@cypress-design/constants-tabs'
import * as SelectConstants from '@cypress-design/constants-select'
import type {
  SelectItem,
  SelectThemingProps,
  SelectHeaderProps,
  SelectSearchProps,
  SelectFooterProps,
  SelectSizingProps,
} from '@cypress-design/constants-select'
import {
  getInteractiveIndices,
  getSelectableIndices,
} from '@cypress-design/constants-select'
import SelectOptionItem from './SelectOptionItem'

// Composed from the same shared groups as SelectProps so the popover's
// chrome (header + search + footer + sizing + theming) stays a single
// source of truth. `items` arrives ALREADY FILTERED — Select owns the
// search query and applies `filterAndCollapseHeadlines` before passing
// the list down, so keyboard nav and rendering agree on which rows exist.
export interface SelectOptionListProps
  extends SelectThemingProps,
    SelectHeaderProps,
    Omit<SelectSearchProps, 'searchFilters'>,
    SelectFooterProps,
    SelectSizingProps {
  items: SelectItem[]
  value?: string
  onSelect: (item: SelectItem) => void
  onHeaderTabChange?: (id: string) => void

  // Controlled search value — Select owns the state and the filter.
  searchValue?: string
  onSearchValueChange?: (value: string) => void

  // React-only: structured footerLabel/footerAction live in SelectFooterProps;
  // the optional ReactNode escape hatch sits alongside them.
  footer?: React.ReactNode

  align?: SelectConstants.SelectAlignment
  id?: string
  className?: string

  // Keyboard-focused row index (within the rendered list).
  // Provided by Select; the panel just renders the state.
  focusedIndex?: number
  itemIdPrefix?: string
}

// React JSX needs a component type to instantiate; the shared
// SelectHeaderProps interface uses IconNode (= unknown) so it stays
// framework-agnostic. Re-narrow at the destructure boundary against the
// design-system Icon prop surface — keeps intellisense honest for header
// icons (size, interactiveColorsOnGroup, className).
type IconComponent = React.ComponentType<
  Omit<OpenIconProps, 'name'> & { className?: string }
>

// Render a consumer-passed IconNode (unknown) whether it's a component
// reference (design-system convention: `IconArrowLeft`) or a rendered
// element (`<IconArrowLeft />`). Instantiating an already-rendered
// element as JSX (`<Icon />`) throws — this helper mirrors the pattern
// in SelectOptionItem so header icons accept the same two shapes as
// option-row icons.
function renderHeaderIcon(Icon: unknown, className: string): React.ReactNode {
  if (!Icon) return null
  if (React.isValidElement(Icon)) {
    return <span className={className}>{Icon}</span>
  }
  if (typeof Icon === 'function') {
    const Component = Icon as IconComponent
    return (
      <Component
        size="16"
        interactiveColorsOnGroup={true}
        className={className}
      />
    )
  }
  return <span className={className}>{Icon as React.ReactNode}</span>
}

export const SelectOptionList: React.FC<SelectOptionListProps> = ({
  items,
  theme = SelectConstants.DefaultTheme,
  size = SelectConstants.DefaultSize,
  value,
  onSelect,
  headerTitle,
  // Icon props are aliased so they can flow through `renderHeaderIcon`,
  // which handles both a component reference (design-system convention)
  // and an already-rendered React element consumers might reasonably pass.
  headerButton: headerButtonRaw,
  headerIconLeft: headerIconLeftRaw,
  headerTag,
  headerIconRight: headerIconRightRaw,
  headerTabs,
  headerActiveTab,
  onHeaderTabChange,
  searchable = false,
  searchPlaceholder = SelectConstants.DefaultSearchPlaceholder,
  searchValue = '',
  onSearchValueChange,
  footer,
  footerLabel,
  footerAction,
  width,
  minWidth,
  maxWidth,
  height,
  maxHeight,
  align = SelectConstants.DefaultAlignment,
  id,
  className,
  focusedIndex,
  itemIdPrefix,
}) => {
  const HeaderButton = headerButtonRaw as
    | { iconLeft: IconComponent; onClick: () => void; ariaLabel?: string }
    | undefined
  const HeaderIconLeft = headerIconLeftRaw as IconComponent | undefined
  const HeaderIconRight = headerIconRightRaw as IconComponent | undefined

  // Two different "navigable" sets for the panel:
  //   * `interactiveIndices` — rows the keyboard can land on (includes
  //     in-list `button` rows so they're keyboard-reachable);
  //   * `selectableIndices`  — rows the user can pick as a value (excludes
  //     buttons). Used only to decide whether to show "No results" — when
  //     search filters out every selectable row, the empty state still
  //     fires even if a button (e.g. "+ Add new") survives the filter.
  const interactiveIndices = React.useMemo(
    () => getInteractiveIndices(items),
    [items],
  )
  const selectableIndices = React.useMemo(
    () => getSelectableIndices(items),
    [items],
  )
  const focusedSelectableIndex =
    typeof focusedIndex === 'number'
      ? interactiveIndices[focusedIndex]
      : undefined
  // Set `aria-activedescendant` on the header search Textbox in addition
  // to the trigger. WAI-ARIA combobox: the attribute must live on the
  // element that has DOM focus — screen readers reading from the search
  // input won't announce the highlighted option if only the trigger
  // carries it. Clamp so a stale `focusedIndex` past a filter shrink
  // doesn't emit `${itemIdPrefix}-undefined` for one frame.
  const activeDescendantId =
    typeof focusedIndex === 'number' &&
    focusedIndex >= 0 &&
    focusedIndex < interactiveIndices.length &&
    itemIdPrefix
      ? `${itemIdPrefix}-${interactiveIndices[focusedIndex]}`
      : undefined

  const hasTitleRow = Boolean(
    headerTitle ||
      HeaderButton ||
      HeaderIconLeft ||
      headerTag ||
      HeaderIconRight,
  )
  const hasTabsOrSearch = Boolean(
    (headerTabs && headerTabs.length > 0) || searchable,
  )
  const hasHeader = hasTitleRow || hasTabsOrSearch
  const hasFooter = Boolean(footer || footerLabel || footerAction)

  const panelStyle = SelectConstants.buildSizingStyle({
    width,
    minWidth,
    maxWidth,
    height,
    maxHeight,
  })

  // The listbox role must wrap ONLY the option items — axe flags
  // `role="listbox"` on a container that also holds non-option children
  // (header buttons, tabs, search input, footer actions). Give the
  // items container its own id (`${popoverId}-listbox`) so the trigger's
  // `aria-controls` can point at it.
  const listboxId = id ? `${id}-listbox` : undefined
  return (
    <div
      id={id}
      style={panelStyle}
      className={clsx(
        SelectConstants.CssPopoverLayoutClasses,
        SelectConstants.CssAlignmentClasses[align],
        SelectConstants.CssPopoverClasses[theme],
        SelectConstants.CssPopoverSizeClasses[size],
        className,
      )}
    >
      {hasHeader && (
        <div className={SelectConstants.CssHeaderContainerClasses}>
          {hasTitleRow && (
            <div
              className={clsx(
                SelectConstants.CssHeaderTitleRowClasses,
                // Title row carries its own bottom border so a separator
                // appears between it and whatever follows (tabs/search
                // bundle, or the items area if nothing else in the header).
                SelectConstants.CssHeaderClasses[theme],
                // 8px from the row edge to the back button so the button
                // hugs the panel edge; 16px when no button so the iconLeft
                // / title sits inset from the edge.
                HeaderButton ? 'pl-[8px]' : 'pl-[16px]',
                // 16px between the iconRight and the panel edge so the
                // icon has breathing room; default 8px when no iconRight.
                HeaderIconRight ? 'pr-[16px]' : 'pr-[8px]',
              )}
            >
              {HeaderButton && (
                <Button
                  size="32"
                  square
                  variant={theme === 'dark' ? 'outline-dark' : 'white'}
                  aria-label={HeaderButton.ariaLabel}
                  onClick={HeaderButton.onClick}
                  className={SelectConstants.CssHeaderBackButtonSpacingClasses}
                >
                  {renderHeaderIcon(HeaderButton.iconLeft, 'shrink-0')}
                </Button>
              )}
              <div className={SelectConstants.CssHeaderTitleGroupClasses}>
                {renderHeaderIcon(
                  headerIconLeftRaw,
                  SelectConstants.CssHeaderIconColorClasses[theme],
                )}
                {headerTitle && (
                  <span
                    className={clsx(
                      SelectConstants.CssHeaderTitleSizeClasses[size],
                      SelectConstants.CssHeaderTitleClasses[theme],
                    )}
                  >
                    {headerTitle}
                  </span>
                )}
                {headerTag && (
                  <Tag size="16" color="gray" dark={theme === 'dark'}>
                    {headerTag}
                  </Tag>
                )}
              </div>
              {renderHeaderIcon(
                headerIconRightRaw,
                SelectConstants.CssHeaderIconColorClasses[theme],
              )}
            </div>
          )}
          {hasTabsOrSearch && (
            <div
              className={clsx(
                SelectConstants.CssHeaderTabsSearchWrapperClasses,
                // Bottom border separates the tabs/search bundle from the
                // items area below.
                SelectConstants.CssHeaderClasses[theme],
              )}
            >
              {headerTabs && headerTabs.length > 0 && (
                // Wrapper keeps Tabs at content width — flex-col parents
                // otherwise stretch every child to the full cross-axis.
                // Dark: `dark-small` at size 32 / `dark-large` at size 40
                // so tabs scale with the row height. Light has no `*-small`
                // pill variant yet, so it stays on `default` for both sizes.
                <div className="self-start">
                  <Tabs
                    variant={
                      theme === 'dark'
                        ? size === '40'
                          ? 'dark-large'
                          : 'dark-small'
                        : 'default'
                    }
                    tabs={headerTabs as Tab[]}
                    activeId={headerActiveTab}
                    onSwitch={(tab) => onHeaderTabChange?.(tab.id)}
                  />
                </div>
              )}
              {searchable && (
                <Textbox
                  theme={theme}
                  size="32"
                  placeholder={searchPlaceholder}
                  iconLeft={IconObjectMagnifyingGlass}
                  value={searchValue}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                    onSearchValueChange?.(e.target.value)
                  }
                  aria-label={searchPlaceholder}
                  aria-activedescendant={activeDescendantId}
                />
              )}
            </div>
          )}
        </div>
      )}

      <div
        id={listboxId}
        role="listbox"
        aria-label={headerTitle || 'Options'}
        className={SelectConstants.CssItemsContainerClasses}
      >
        {/* Show "No results" only when an active search filter left zero
            *selectable* rows. `searchValue` gates out the false-positive
            on purely-structural panels (headline + divider only, no
            search typed) where the banner would read as an error.
            `selectableIndices` (not `interactiveIndices`) is
            deliberate: the filter keeps standalone divider and button
            rows (so a "+ Add new" action stays visible during search),
            and those rows shouldn't suppress the banner — the user
            still has nothing they can actually pick. A disabled row
            that matched the query by label counts as a visible-but-
            unselectable result and (accepted trade-off) shows the
            banner alongside it. */}
        {searchValue && selectableIndices.length === 0 && (
          <div className={SelectConstants.CssEmptyStateClasses[theme]}>
            No results
          </div>
        )}
        {items.map((item, index) => {
          const itemValue = SelectConstants.getItemValue(item)
          // Empty string is a valid `value` per `SelectItemDefault` —
          // `itemValue === value` already excludes `undefined` ↔ '' (since
          // `'' !== undefined`), so no extra guard is needed.
          const selected = itemValue !== undefined && itemValue === value
          const focused = index === focusedSelectableIndex
          const rowId = itemIdPrefix ? `${itemIdPrefix}-${index}` : undefined
          const key = (() => {
            if ('key' in item && item.key) return item.key
            // Empty string is a valid `value` (selection treats it as such);
            // use `!== undefined` rather than a truthy check so a row with
            // `value: ''` doesn't fall back to the type-and-index key and
            // unnecessarily remount when items reorder.
            if (itemValue !== undefined) return itemValue
            return `${item.type ?? 'default'}-${index}`
          })()
          return (
            <SelectOptionItem
              key={key}
              id={rowId}
              item={item}
              theme={theme}
              size={size}
              selected={selected}
              focused={focused}
              onSelect={onSelect}
            />
          )
        })}
      </div>

      {hasFooter && (
        <div
          className={clsx(
            SelectConstants.CssFooterContainerClasses,
            SelectConstants.CssFooterClasses[theme],
          )}
        >
          {footer ?? (
            <>
              {footerLabel && (
                <span className={SelectConstants.CssFooterLabelGroupClasses}>
                  <IconActionInfoOutline
                    size="16"
                    interactiveColorsOnGroup={true}
                    className={SelectConstants.CssFooterIconColorClasses[theme]}
                  />
                  <span
                    className={SelectConstants.CssFooterLabelClasses[theme]}
                  >
                    {footerLabel}
                  </span>
                </span>
              )}
              {footerAction && (
                <Button
                  size="24"
                  // Theme-aware default: `link` reads as a subtle textual link
                  // on light, but vanishes against the dark footer band — use
                  // the `outline-dark` variant there so it stays visible.
                  variant={theme === 'dark' ? 'outline-dark' : 'link'}
                  onClick={footerAction.onClick}
                >
                  {footerAction.label}
                </Button>
              )}
            </>
          )}
        </div>
      )}
    </div>
  )
}

export default SelectOptionList

// components/Select/vue/_SelectOptionList.vue
<script lang="ts" setup>
import {
  computed,
  defineComponent,
  h,
  isVNode,
  type PropType,
  type VNode,
} from 'vue'
import Tabs from '@cypress-design/vue-tabs'
import type { Tab } from '@cypress-design/constants-tabs'
import Textbox from '@cypress-design/vue-textbox'
import Button from '@cypress-design/vue-button'
import Tag from '@cypress-design/vue-tag'
import {
  IconObjectMagnifyingGlass,
  IconActionInfoOutline,
} from '@cypress-design/vue-icon'
import * as SelectConstants from '@cypress-design/constants-select'
import {
  getInteractiveIndices,
  getSelectableIndices,
} from '@cypress-design/constants-select'
import type {
  SelectItem,
  SelectAlignment,
  SelectThemingProps,
  SelectHeaderProps,
  SelectSearchProps,
  SelectFooterProps,
  SelectSizingProps,
} from '@cypress-design/constants-select'
import SelectOptionItem from './_SelectOptionItem.vue'

// `IconNode = unknown` — mirror React's two-shape dispatcher so a
// consumer that passes an already-rendered VNode (from `h()` or JSX) to
// `headerButton.iconLeft` / `headerIconLeft` / `headerIconRight` renders
// alongside consumers that pass a component reference. `<component :is>`
// alone can't handle both because Vue's dynamic-component runtime
// expects a component definition, not a rendered node.
const IconRender = defineComponent({
  props: {
    icon: { required: true },
    size: { type: String as PropType<'16' | '24'>, default: '16' },
    class: { type: [String, Array, Object], default: undefined },
  },
  setup(props) {
    return () => {
      const icon = props.icon
      if (!icon) return null
      if (isVNode(icon)) return h('span', { class: props.class as any }, [icon])
      if (typeof icon === 'function' || typeof icon === 'object') {
        return h(icon as any, {
          size: props.size,
          interactiveColorsOnGroup: true,
          class: props.class,
        })
      }
      return h('span', { class: props.class as any }, [icon as any])
    }
  },
})

// Props share the same named groups as Select.vue so adding a header /
// search / footer / sizing field happens in one place
// (@cypress-design/constants-select). `items` arrives ALREADY FILTERED —
// Select owns `searchValue` and applies `filterAndCollapseHeadlines`
// before passing the list down, so keyboard nav and rendering agree on
// which rows exist.
type OptionListProps = SelectThemingProps &
  SelectHeaderProps &
  Omit<SelectSearchProps, 'searchFilters'> &
  SelectFooterProps &
  SelectSizingProps & {
    items: SelectItem[]
    value?: string
    // Controlled search input value — Select owns the state and the filter.
    searchValue?: string
    align?: SelectAlignment
    id?: string
    panelClass?: string
    focusedIndex?: number
    itemIdPrefix?: string
  }

const props = withDefaults(defineProps<OptionListProps>(), {
  theme: SelectConstants.DefaultTheme,
  size: SelectConstants.DefaultSize,
  align: SelectConstants.DefaultAlignment,
  searchable: false,
  searchPlaceholder: SelectConstants.DefaultSearchPlaceholder,
  searchValue: '',
})

const emit = defineEmits<{
  (e: 'select', item: SelectItem): void
  (e: 'header-tab-change', id: string): void
  (e: 'update:searchValue', value: string): void
}>()

defineSlots<{
  footer?: () => VNode[]
}>()

function onHeaderTabSwitch(tab: { id: string }) {
  emit('header-tab-change', tab.id)
}

// Two different "navigable" sets for the panel:
//   * `interactiveIndices` — rows the keyboard can land on (includes
//     in-list `button` rows so they're keyboard-reachable);
//   * `selectableIndices`  — rows the user can pick as a value (excludes
//     buttons). Used only to decide whether to show "No results" — when
//     search filters out every selectable row, the empty state still
//     fires even if a button (e.g. "+ Add new") survives the filter.
const interactiveIndices = computed(() => getInteractiveIndices(props.items))
const selectableIndices = computed(() => getSelectableIndices(props.items))
const focusedSelectableIndex = computed(() =>
  typeof props.focusedIndex === 'number'
    ? interactiveIndices.value[props.focusedIndex]
    : undefined,
)
// Set `aria-activedescendant` on the header search Textbox in addition
// to the trigger. WAI-ARIA combobox: the attribute must live on the
// element that has DOM focus — screen readers reading from the search
// input won't announce the highlighted option if only the trigger
// carries it. Clamp so a stale `focusedIndex` past a filter shrink
// doesn't emit `${itemIdPrefix}-undefined` for one frame.
const activeDescendantId = computed(() => {
  const i = props.focusedIndex
  if (typeof i !== 'number' || i < 0) return undefined
  if (i >= interactiveIndices.value.length) return undefined
  if (!props.itemIdPrefix) return undefined
  return `${props.itemIdPrefix}-${interactiveIndices.value[i]}`
})

const hasTitleRow = computed(
  () =>
    !!props.headerTitle ||
    !!props.headerButton ||
    !!props.headerIconLeft ||
    !!props.headerTag ||
    !!props.headerIconRight,
)
const hasTabsOrSearch = computed(
  () => (props.headerTabs && props.headerTabs.length > 0) || props.searchable,
)
const hasHeader = computed(() => hasTitleRow.value || hasTabsOrSearch.value)
const hasFooter = computed(() => !!props.footerLabel || !!props.footerAction)

const panelStyle = computed(() =>
  SelectConstants.buildSizingStyle({
    width: props.width,
    minWidth: props.minWidth,
    maxWidth: props.maxWidth,
    height: props.height,
    maxHeight: props.maxHeight,
  }),
)

const panelClasses = computed(() => [
  SelectConstants.CssPopoverLayoutClasses,
  SelectConstants.CssAlignmentClasses[props.align],
  SelectConstants.CssPopoverClasses[props.theme],
  SelectConstants.CssPopoverSizeClasses[props.size],
  props.panelClass,
])

function itemValueOf(item: SelectItem): string | undefined {
  return SelectConstants.getItemValue(item)
}

function itemKey(item: SelectItem, index: number): string {
  if ('key' in item && (item as { key?: string }).key) {
    return (item as { key: string }).key
  }
  const v = itemValueOf(item)
  // Empty string is a valid `value` (selection treats it as such); use
  // `!== undefined` rather than a truthy check so a row with `value: ''`
  // doesn't fall back to the type-and-index key and unnecessarily remount
  // when items reorder.
  if (v !== undefined) return v
  return `${item.type ?? 'default'}-${index}`
}

function rowId(index: number): string | undefined {
  return props.itemIdPrefix ? `${props.itemIdPrefix}-${index}` : undefined
}

// The listbox role must wrap ONLY the option items — axe flags
// `role="listbox"` on a container that also holds non-option children
// (header buttons, tabs, search input, footer actions). Give the items
// container its own id (`${popoverId}-listbox`) so the trigger's
// `aria-controls` can point at it.
const listboxId = computed(() => (props.id ? `${props.id}-listbox` : undefined))
</script>

<template>
  <div :id="id" :style="panelStyle" :class="panelClasses">
    <div v-if="hasHeader" :class="SelectConstants.CssHeaderContainerClasses">
      <!-- Title row: button · iconLeft · title · tag · (spacer) · iconRight.
           Carries its own bottom border so a separator appears between the
           title row and whatever follows it (tabs/search bundle, or the
           items area when there's nothing else in the header).
           Horizontal padding varies with content — see comments next to the
           inline `pl-*` / `pr-*` classes below. -->
      <div
        v-if="hasTitleRow"
        :class="[
          SelectConstants.CssHeaderTitleRowClasses,
          SelectConstants.CssHeaderClasses[theme],
          headerButton ? 'pl-[8px]' : 'pl-[16px]',
          headerIconRight ? 'pr-[16px]' : 'pr-[8px]',
        ]"
      >
        <Button
          v-if="headerButton"
          size="32"
          square
          :variant="theme === 'dark' ? 'outline-dark' : 'white'"
          :aria-label="headerButton.ariaLabel"
          :class="SelectConstants.CssHeaderBackButtonSpacingClasses"
          @click="headerButton.onClick()"
        >
          <IconRender :icon="headerButton.iconLeft" size="16" />
        </Button>
        <div :class="SelectConstants.CssHeaderTitleGroupClasses">
          <IconRender
            v-if="headerIconLeft"
            :icon="headerIconLeft"
            size="16"
            :class="SelectConstants.CssHeaderIconColorClasses[theme]"
          />
          <span
            v-if="headerTitle"
            :class="[
              SelectConstants.CssHeaderTitleSizeClasses[size],
              SelectConstants.CssHeaderTitleClasses[theme],
            ]"
          >
            {{ headerTitle }}
          </span>
          <Tag v-if="headerTag" size="16" color="gray" :dark="theme === 'dark'">
            {{ headerTag }}
          </Tag>
        </div>
        <IconRender
          v-if="headerIconRight"
          :icon="headerIconRight"
          size="16"
          :class="SelectConstants.CssHeaderIconColorClasses[theme]"
        />
      </div>
      <!-- Tabs + search bundle: their own padding context below the title row.
           Bottom border separates the bundle from the items area below. -->
      <div
        v-if="hasTabsOrSearch"
        :class="[
          SelectConstants.CssHeaderTabsSearchWrapperClasses,
          SelectConstants.CssHeaderClasses[theme],
        ]"
      >
        <!-- Wrapper keeps Tabs at content width — flex-col parents otherwise
             stretch every child to the full cross-axis (panel width).
             Dark: `dark-small` at size 32 / `dark-large` at size 40 so the
             tabs scale with the row height. Light has no `*-small` pill
             variant yet, so it stays on `default` for both sizes. -->
        <div v-if="headerTabs && headerTabs.length > 0" class="self-start">
          <Tabs
            :variant="
              theme === 'dark'
                ? size === '40'
                  ? 'dark-large'
                  : 'dark-small'
                : 'default'
            "
            :tabs="headerTabs as Tab[]"
            :active-id="headerActiveTab"
            @switch="onHeaderTabSwitch"
          />
        </div>
        <Textbox
          v-if="searchable"
          :model-value="searchValue"
          :theme="theme"
          size="32"
          :placeholder="searchPlaceholder"
          :icon-left="IconObjectMagnifyingGlass"
          :aria-label="searchPlaceholder"
          :aria-activedescendant="activeDescendantId"
          @update:model-value="(v: string) => emit('update:searchValue', v)"
        />
      </div>
    </div>

    <div
      :id="listboxId"
      role="listbox"
      :aria-label="headerTitle || 'Options'"
      :class="SelectConstants.CssItemsContainerClasses"
    >
      <!-- Show "No results" only when an active search filter left zero
           *selectable* rows. `searchValue` gates out the false-positive
           on purely-structural panels (headline + divider only, no
           search typed) where the banner would read as an error.
           `selectableIndices` (not `interactiveIndices`) is deliberate:
           the filter keeps standalone divider and button rows (so a
           "+ Add new" action stays visible during search), and those
           rows shouldn't suppress the banner — the user still has
           nothing they can actually pick. A disabled row that matched
           the query by label counts as a visible-but-unselectable
           result and (accepted trade-off) shows the banner alongside
           it. -->
      <div
        v-if="searchValue && selectableIndices.length === 0"
        :class="SelectConstants.CssEmptyStateClasses[theme]"
      >
        No results
      </div>
      <SelectOptionItem
        v-for="(item, index) in items"
        :id="rowId(index)"
        :key="itemKey(item, index)"
        :item="item"
        :theme="theme"
        :size="size"
        :selected="
          itemValueOf(item) !== undefined && itemValueOf(item) === value
        "
        :focused="index === focusedSelectableIndex"
        @select="(it: SelectItem) => emit('select', it)"
      />
    </div>

    <div
      v-if="hasFooter || $slots.footer"
      :class="[
        SelectConstants.CssFooterContainerClasses,
        SelectConstants.CssFooterClasses[theme],
      ]"
    >
      <slot name="footer">
        <span
          v-if="footerLabel"
          :class="SelectConstants.CssFooterLabelGroupClasses"
        >
          <IconActionInfoOutline
            size="16"
            :interactive-colors-on-group="true"
            :class="SelectConstants.CssFooterIconColorClasses[theme]"
          />
          <span :class="SelectConstants.CssFooterLabelClasses[theme]">
            {{ footerLabel }}
          </span>
        </span>
        <Button
          v-if="footerAction"
          size="24"
          :variant="theme === 'dark' ? 'outline-dark' : 'link'"
          @click="footerAction.onClick()"
        >
          {{ footerAction.label }}
        </Button>
      </slot>
    </div>
  </div>
</template>
