// components/RunResults/react/RunResults.tsx
import * as React from 'react'
import clsx from 'clsx'
import { twMerge } from 'tailwind-merge'
import StatusIcon from '@cypress-design/react-statusicon'
import {
  IconStatusFlaky,
  IconGeneralSparkleSingle,
  IconTechnologyBranchH,
} from '@cypress-design/react-icon'
import Tooltip from '@cypress-design/react-tooltip'
import {
  CssClasses,
  CssTheme,
  CssTooltipPopperDark,
  CssTooltipPopperLight,
  TooltipColorForTheme,
  RUN_STATUS_VARIANTS,
  RUN_STATUS_TEXT_CLASSES,
  RUN_STATUS_BORDER_CLASSES,
  RUN_STATUS_LABELS,
  warnInvalidRunStatus,
  type RunResultsProps,
  type RunResultsTheme,
  type RunStatusConfig,
  type StatKey,
  getSeparatorAfterKey,
  getTooltipLabel,
  getTooltipPlacement,
  getFlakyTooltipText,
  hasAnyStat,
  showRegularStat,
  statKeyToKebab,
  statValue,
} from '@cypress-design/constants-runresults'

export type {
  RunResultsProps,
  RunStatusConfig,
  RunStatusKey,
} from '@cypress-design/constants-runresults'

interface StatProps {
  statKey: StatKey
  count: number
  link: string | undefined
  renderLink: RunResultsProps['renderLink']
  showTooltip: boolean
  theme: RunResultsTheme
  applySeparator: boolean
}

const Stat: React.FC<StatProps> = ({
  statKey,
  count,
  link,
  renderLink,
  showTooltip,
  theme,
  applySeparator,
}) => {
  const kebab = statKeyToKebab(statKey)
  const isLinked = !!link
  const label = getTooltipLabel(statKey, count, isLinked)

  const icon = (() => {
    if (statKey === 'flaky') {
      return (
        <IconStatusFlaky
          size="12"
          data-cy="status-icon-flaky"
          className={CssClasses.iconFlaky}
        />
      )
    }
    if (statKey === 'selfHealed') {
      return (
        <IconGeneralSparkleSingle
          size="12"
          strokeColor="jade-400"
          fillColor="jade-50"
          data-cy="status-icon-self-healed"
          className={CssClasses.iconSelfHealed}
        />
      )
    }
    return (
      <StatusIcon
        size="12"
        status={statKey}
        data-cy={`status-icon-${kebab}`}
        className={CssClasses.icon}
      />
    )
  })()

  const inner = (
    <>
      {icon}
      <span>{count}</span>
    </>
  )

  const linkClasses = clsx(CssClasses.link, CssTheme[theme].link)
  const unlinkedClasses = CssClasses.unlinked

  let content: React.ReactNode
  if (isLinked && link) {
    if (renderLink) {
      content = renderLink(link, inner, linkClasses) as React.ReactNode
    } else {
      content = (
        <a
          href={link}
          aria-label={label}
          data-cy={`link-${kebab}`}
          className={linkClasses}
        >
          {inner}
        </a>
      )
    }
  } else {
    content = <span className={unlinkedClasses}>{inner}</span>
  }

  const tooltipText = statKey === 'flaky' ? getFlakyTooltipText(count) : label

  const wrappedContent = showTooltip ? (
    <Tooltip
      placement={getTooltipPlacement(statKey)}
      color={TooltipColorForTheme[theme]}
      popper={tooltipText}
      popperClassName={
        TooltipColorForTheme[theme] === 'dark'
          ? CssTooltipPopperDark
          : CssTooltipPopperLight
      }
    >
      {content}
    </Tooltip>
  ) : (
    content
  )

  return (
    <li
      data-cy={`total-${kebab}`}
      className={clsx(
        CssClasses.item,
        applySeparator && CssClasses.separatorAfter,
        applySeparator && CssTheme[theme].separator,
      )}
    >
      {wrappedContent}
    </li>
  )
}

interface RunStatusSegmentProps {
  kind: 'build-number' | 'branch'
  icon: React.ReactNode
  label: React.ReactNode
  href: string | undefined
  ariaLabel: string
  renderLink: RunResultsProps['renderLink']
  theme: RunResultsTheme
  applyDivider: boolean
}

const RunStatusSegment: React.FC<RunStatusSegmentProps> = ({
  kind,
  icon,
  label,
  href,
  ariaLabel,
  renderLink,
  theme,
  applyDivider,
}) => {
  const isLinked = !!href
  const segmentBase = clsx(
    CssClasses.runStatusSegment,
    applyDivider && CssClasses.runStatusDivider,
    applyDivider && CssTheme[theme].runStatusDivider,
    applyDivider && CssClasses.runStatusSegmentDividerAdjacent,
  )
  const linkClasses = clsx(
    segmentBase,
    CssClasses.runStatusLink,
    CssTheme[theme].runStatusLink,
  )
  const unlinkedClasses = segmentBase

  const inner = (
    <>
      {icon}
      {label}
    </>
  )

  if (isLinked && href) {
    if (renderLink) {
      return renderLink(href, inner, linkClasses) as React.ReactElement
    }
    return (
      <a
        href={href}
        aria-label={ariaLabel}
        data-cy={`run-status-${kind}`}
        className={linkClasses}
      >
        {inner}
      </a>
    )
  }
  return (
    <span data-cy={`run-status-${kind}`} className={unlinkedClasses}>
      {inner}
    </span>
  )
}

interface RunStatusPillProps {
  config: RunStatusConfig
  renderLink: RunResultsProps['renderLink']
  theme: RunResultsTheme
}

const RunStatusPill: React.FC<RunStatusPillProps> = ({
  config,
  renderLink,
  theme,
}) => {
  const {
    buildNumber,
    status,
    branch,
    variant = 'base',
    href,
    pillClassName,
  } = config

  // Defense-in-depth guard against runtime data drift (e.g. an un-mapped
  // domain enum sneaking past TypeScript). The outer `showRunStatus` gate in
  // `RunResults` already prevents mounting this component with an invalid
  // status — and emits the dev warning via `warnInvalidRunStatus` — so this
  // branch is unreachable in normal use. Kept in case a future refactor
  // exposes `RunStatusPill` directly.
  const iconConfig = RUN_STATUS_VARIANTS[status]
  if (!iconConfig) return null
  const { variant: iconVariant, size: iconSize } = iconConfig
  const isLink = variant === 'link'

  const pillClasses = twMerge(
    CssClasses.runStatusPill,
    CssTheme[theme].runStatusPill,
    isLink && RUN_STATUS_BORDER_CLASSES[status],
    pillClassName,
  )

  // Build-number segment: status icon + #N (with status-colored text).
  const buildNumberIcon = (
    <StatusIcon
      size={iconSize}
      status={status}
      variant={iconVariant}
      data-cy="run-status-icon"
      className={CssClasses.runStatusIcon}
    />
  )
  const buildNumberLabel = (
    <span className={RUN_STATUS_TEXT_CLASSES[status]}>{`#${buildNumber}`}</span>
  )

  // Branch segment: branch icon + branch text (in neutral theme color).
  const hasBranch = !!branch
  const branchIcon = hasBranch ? (
    <IconTechnologyBranchH
      size="16"
      strokeColor="gray-500"
      data-cy="run-status-branch-icon"
      className={CssClasses.runStatusIcon}
    />
  ) : null
  const branchLabel = hasBranch ? (
    <span
      className={clsx(
        CssClasses.runStatusBranchText,
        CssTheme[theme].runStatusBranchText,
      )}
    >
      {branch}
    </span>
  ) : null

  return (
    <span
      data-cy="run-status"
      title={RUN_STATUS_LABELS[status]}
      className={pillClasses}
    >
      <RunStatusSegment
        kind="build-number"
        icon={buildNumberIcon}
        label={buildNumberLabel}
        href={href}
        ariaLabel={`View run #${buildNumber}`}
        renderLink={renderLink}
        theme={theme}
        applyDivider={hasBranch}
      />
      {hasBranch && (
        <RunStatusSegment
          kind="branch"
          icon={branchIcon}
          label={branchLabel}
          href={undefined}
          ariaLabel=""
          renderLink={renderLink}
          theme={theme}
          applyDivider={false}
        />
      )}
    </span>
  )
}

// `forwardRef` so a parent can attach a `ref` to the root wrapper `<div>`.
export const RunResults = React.forwardRef<
  HTMLDivElement,
  RunResultsProps &
    Omit<React.HTMLAttributes<HTMLDivElement>, keyof RunResultsProps>
>(function RunResults(
  {
    runStatus,
    passed,
    failed,
    skipped,
    pending,
    flaky,
    selfHealed,
    showSelfHealed = false,
    theme = 'light',
    expanded = false,
    links,
    renderLink,
    showTooltip = true,
    className,
    pillClassName,
    ...rest
  },
  ref,
) {
  const summaryProps = {
    passed,
    failed,
    skipped,
    pending,
    flaky,
    selfHealed,
    showSelfHealed,
    expanded,
  }

  const showTestCounts = hasAnyStat(summaryProps)
  // The run-status pill only renders when `status` is a valid `RunStatusKey`
  // (see also the defense-in-depth guard in `RunStatusPill`). Gate
  // `showRunStatus` on the same check so a `runStatus` with an invalid
  // status doesn't produce an empty root wrapper when the test-counts pill
  // is also empty. Warn once in dev when we skip due to a bad status
  // (deduped inside `warnInvalidRunStatus`).
  const showRunStatus = !!runStatus && !!RUN_STATUS_VARIANTS[runStatus.status]
  if (runStatus && !showRunStatus) warnInvalidRunStatus(runStatus.status)

  // Both pills empty → render nothing. See instructions.md "Empty state".
  if (!showRunStatus && !showTestCounts) return null

  const separatorAfterKey = getSeparatorAfterKey(summaryProps)
  const showFlaky = statValue(flaky) > 0
  // Self-healed renders whenever the flag is true; the count (0 included) is
  // shown verbatim. See instructions.md / architecture.md for rationale.
  const showSelfHealedStat = !!showSelfHealed

  return (
    // The wrapper `<div>` is the root. Holds up to two pills:
    //   1. run-status pill (rendered when `runStatus` is set)
    //   2. test-counts pill (rendered when `hasAnyStat` is true)
    // `className` lands here per DS convention. `pillClassName` lands on the
    // test-counts `<ul>`; `runStatus.pillClassName` lands on the run-status
    // `<span>`. Both merged via `tailwind-merge` so consumer overrides win
    // the Tailwind source-order conflict against the theme.
    <div
      ref={ref}
      {...rest}
      // `data-cy` is set AFTER `{...rest}` so a consumer passing their own
      // `data-cy` cannot override our fixed selector. This matches the Vue
      // side and preserves the documented public test contract — see the
      // `[data-cy="run-results"]` row in instructions.md.
      data-cy="run-results"
      className={clsx(CssClasses.container, className)}
    >
      {showRunStatus && (
        <RunStatusPill
          config={runStatus as RunStatusConfig}
          renderLink={renderLink}
          theme={theme}
        />
      )}
      {showTestCounts && (
        <ul
          className={twMerge(
            CssClasses.list,
            CssTheme[theme].list,
            pillClassName,
          )}
        >
          {showFlaky && (
            <Stat
              statKey="flaky"
              count={statValue(flaky)}
              link={links?.flaky}
              renderLink={renderLink}
              showTooltip={showTooltip}
              theme={theme}
              applySeparator={separatorAfterKey === 'flaky'}
            />
          )}
          {showSelfHealedStat && (
            <Stat
              statKey="selfHealed"
              count={statValue(selfHealed)}
              link={links?.selfHealed}
              renderLink={renderLink}
              showTooltip={showTooltip}
              theme={theme}
              applySeparator={separatorAfterKey === 'selfHealed'}
            />
          )}
          {showRegularStat(skipped, expanded) && (
            <Stat
              statKey="skipped"
              count={statValue(skipped)}
              link={links?.skipped}
              renderLink={renderLink}
              showTooltip={showTooltip}
              theme={theme}
              applySeparator={false}
            />
          )}
          {showRegularStat(pending, expanded) && (
            <Stat
              statKey="pending"
              count={statValue(pending)}
              link={links?.pending}
              renderLink={renderLink}
              showTooltip={showTooltip}
              theme={theme}
              applySeparator={false}
            />
          )}
          {showRegularStat(passed, expanded) && (
            <Stat
              statKey="passed"
              count={statValue(passed)}
              link={links?.passed}
              renderLink={renderLink}
              showTooltip={showTooltip}
              theme={theme}
              applySeparator={false}
            />
          )}
          {showRegularStat(failed, expanded) && (
            <Stat
              statKey="failed"
              count={statValue(failed)}
              link={links?.failed}
              renderLink={renderLink}
              showTooltip={showTooltip}
              theme={theme}
              applySeparator={false}
            />
          )}
        </ul>
      )}
    </div>
  )
})

export default RunResults

// components/RunResults/vue/RunResults.vue
<script lang="ts">
import { defineComponent, h, type PropType, type VNode } from 'vue'
import { StatusIcon } from '@cypress-design/vue-statusicon'
import {
  IconStatusFlaky,
  IconGeneralSparkleSingle,
  IconTechnologyBranchH,
} from '@cypress-design/vue-icon'
import Tooltip from '@cypress-design/vue-tooltip'

// RunResults-only tooltip overrides.
//
// The shared Tooltip hardcodes 16px / 24px / 160px-min on its inner text
// container and gray-900 / white text color on the colored wrapper. The
// popper slot only lets us inject content *inside* the inner container, so
// font and color could be set via a child wrapper, but min-width on a
// parent cannot be overridden from a child.
//
// We tag the popper slot content with a marker class
// (`cy-runresults-tooltip-${color}` — e.g. `cy-runresults-tooltip-dark` or
// `cy-runresults-tooltip-light` — applied in the popper slot below) and use
// `:has()` to target the tooltip ancestors only when our marker is present.
// The CSS lives here as a JS-injected <style> tag so consumers of
// @cypress-design/vue-runresults get the overrides without needing to import
// a separate CSS file. SFC <style> blocks would emit a separate
// dist/style.css that the JS bundle doesn't reference under Vite library
// mode — so we inject at runtime.
//
// Color values are hard-coded so the rules work outside the docs site,
// where the --cy-* CSS custom properties may not be loaded:
//   gray-300 (#bfc2d4) for dark tooltips (on light RunResults)
//   gray-700 (#5a5f7a) for light tooltips (on dark RunResults)
const RUN_RESULTS_TOOLTIP_STYLE_ID = 'cy-runresults-tooltip-style'
if (typeof document !== 'undefined') {
  if (!document.getElementById(RUN_RESULTS_TOOLTIP_STYLE_ID)) {
    const style = document.createElement('style')
    style.id = RUN_RESULTS_TOOLTIP_STYLE_ID
    // gray-300 (#BFC2D4) for dark tooltips (on light RunResults)
    // gray-700 (#5A5F7A) for light tooltips (on dark RunResults)
    const sizeRules =
      ' font-size: 14px; line-height: 20px; min-width: 0; white-space: nowrap; '
    style.textContent =
      "[role='tooltip']:has(.cy-runresults-tooltip-dark) > div { color: #bfc2d4; }" +
      "[role='tooltip']:has(.cy-runresults-tooltip-dark) > div > div:last-child {" +
      sizeRules +
      '}' +
      "[role='tooltip']:has(.cy-runresults-tooltip-light) > div { color: #5a5f7a; }" +
      "[role='tooltip']:has(.cy-runresults-tooltip-light) > div > div:last-child {" +
      sizeRules +
      '}'
    document.head.appendChild(style)
  }
}
import {
  CssClasses,
  CssTheme,
  TooltipColorForTheme,
  RUN_STATUS_VARIANTS,
  RUN_STATUS_TEXT_CLASSES,
  RUN_STATUS_BORDER_CLASSES,
  RUN_STATUS_LABELS,
  warnInvalidRunStatus,
  type RunResultsProps,
  type RunResultsTheme,
  type RunStatusConfig,
  type StatKey,
  getSeparatorAfterKey,
  getTooltipLabel,
  getTooltipPlacement,
  getFlakyTooltipText,
  hasAnyStat,
  showRegularStat,
  statKeyToKebab,
  statValue,
} from '@cypress-design/constants-runresults'
import { twMerge } from 'tailwind-merge'

export type {
  RunResultsProps,
  RunStatusConfig,
  RunStatusKey,
} from '@cypress-design/constants-runresults'

// Rendered via a render function rather than <template> because the
// `renderLink` callback prop returns a VNode — template ergonomics don't
// compose cleanly around a caller-provided VNode.
export default defineComponent({
  name: 'RunResults',
  inheritAttrs: false,
  props: {
    // Run-status pill — rendered when provided. See RunStatusConfig.
    runStatus: {
      type: Object as PropType<RunStatusConfig>,
      default: undefined,
    },
    // Number-or-null props use the [Number, null] array form so Vue's
    // runtime validator accepts `null` without emitting a dev-mode type
    // warning. The bare `Number` constructor only matches numbers; the
    // PropType cast is TypeScript-only.
    // All four counts are optional (default null = 0) so callers can render
    // only the run-status pill.
    passed: { type: [Number, null] as PropType<number | null>, default: null },
    failed: { type: [Number, null] as PropType<number | null>, default: null },
    skipped: {
      type: [Number, null] as PropType<number | null>,
      default: null,
    },
    pending: {
      type: [Number, null] as PropType<number | null>,
      default: null,
    },
    flaky: { type: [Number, null] as PropType<number | null>, default: null },
    selfHealed: {
      type: [Number, null] as PropType<number | null>,
      default: null,
    },
    showSelfHealed: { type: Boolean, default: false },
    theme: { type: String as PropType<RunResultsTheme>, default: 'light' },
    expanded: { type: Boolean, default: false },
    links: {
      type: Object as PropType<RunResultsProps['links']>,
      default: () => ({}),
    },
    renderLink: {
      type: Function as PropType<RunResultsProps['renderLink']>,
      default: null,
    },
    showTooltip: { type: Boolean, default: true },
    className: { type: String, default: undefined },
    pillClassName: { type: String, default: undefined },
  },
  setup(props, { attrs }) {
    function joinClasses(...parts: (string | false | undefined)[]): string {
      return parts.filter(Boolean).join(' ')
    }

    function renderIcon(statKey: StatKey): VNode {
      const kebab = statKeyToKebab(statKey)
      if (statKey === 'flaky') {
        return h(IconStatusFlaky, {
          size: '12',
          'data-cy': 'status-icon-flaky',
          class: CssClasses.iconFlaky,
        })
      }
      if (statKey === 'selfHealed') {
        return h(IconGeneralSparkleSingle, {
          size: '12',
          strokeColor: 'jade-400',
          fillColor: 'jade-50',
          'data-cy': 'status-icon-self-healed',
          class: CssClasses.iconSelfHealed,
        })
      }
      return h(StatusIcon, {
        size: '12',
        status: statKey,
        'data-cy': `status-icon-${kebab}`,
        class: CssClasses.icon,
      })
    }

    function renderStat(
      statKey: StatKey,
      count: number,
      link: string | undefined,
      applySeparator: boolean,
    ): VNode {
      const kebab = statKeyToKebab(statKey)
      const isLinked = !!link
      const label = getTooltipLabel(statKey, count, isLinked)
      const inner: VNode[] = [renderIcon(statKey), h('span', String(count))]

      let content: VNode
      if (link) {
        const linkClasses = joinClasses(
          CssClasses.link,
          CssTheme[props.theme].link,
        )
        if (props.renderLink) {
          content = props.renderLink(link, inner, linkClasses) as VNode
        } else {
          content = h(
            'a',
            {
              href: link,
              'aria-label': label,
              'data-cy': `link-${kebab}`,
              class: linkClasses,
            },
            inner,
          )
        }
      } else {
        content = h('span', { class: CssClasses.unlinked }, inner)
      }

      if (props.showTooltip) {
        const tooltipText =
          statKey === 'flaky' ? getFlakyTooltipText(count) : label
        const tooltipTarget = content
        content = h(
          Tooltip,
          {
            placement: getTooltipPlacement(statKey),
            color: TooltipColorForTheme[props.theme],
          },
          {
            default: () => tooltipTarget,
            // Marker class — picked up by the injected <style> above to apply
            // RunResults-only tooltip overrides per tooltip color variant.
            popper: () =>
              h(
                'span',
                {
                  class: `cy-runresults-tooltip-${TooltipColorForTheme[props.theme]}`,
                },
                tooltipText,
              ),
          },
        )
      }

      return h(
        'li',
        {
          'data-cy': `total-${kebab}`,
          class: joinClasses(
            CssClasses.item,
            applySeparator && CssClasses.separatorAfter,
            applySeparator && CssTheme[props.theme].separator,
          ),
        },
        [content],
      )
    }

    function renderRunStatusSegment(
      kind: 'build-number' | 'branch',
      icon: VNode,
      label: VNode,
      href: string | undefined,
      ariaLabel: string,
      applyDivider: boolean,
    ): VNode {
      const segmentBase = joinClasses(
        CssClasses.runStatusSegment,
        applyDivider && CssClasses.runStatusDivider,
        applyDivider && CssTheme[props.theme].runStatusDivider,
        applyDivider && CssClasses.runStatusSegmentDividerAdjacent,
      )
      const inner: VNode[] = [icon, label]

      if (href) {
        const linkClasses = joinClasses(
          segmentBase,
          CssClasses.runStatusLink,
          CssTheme[props.theme].runStatusLink,
        )
        if (props.renderLink) {
          return props.renderLink(href, inner, linkClasses) as VNode
        }
        return h(
          'a',
          {
            href,
            'aria-label': ariaLabel,
            'data-cy': `run-status-${kind}`,
            class: linkClasses,
          },
          inner,
        )
      }
      return h(
        'span',
        {
          'data-cy': `run-status-${kind}`,
          class: segmentBase,
        },
        inner,
      )
    }

    function renderRunStatusPill(config: RunStatusConfig): VNode | null {
      const {
        buildNumber,
        status,
        branch,
        variant = 'base',
        href,
        pillClassName,
      } = config

      // Defense-in-depth guard against runtime data drift (e.g. an un-mapped
      // domain enum sneaking past TypeScript). The outer `showRunStatus`
      // gate below already prevents this function running with an invalid
      // status — and emits the dev warning via `warnInvalidRunStatus` — so
      // this branch is unreachable in normal use. Kept in case a future
      // refactor calls `renderRunStatusPill` directly.
      const iconConfig = RUN_STATUS_VARIANTS[status]
      if (!iconConfig) return null
      const { variant: iconVariant, size: iconSize } = iconConfig
      const isLink = variant === 'link'

      const pillClasses = twMerge(
        CssClasses.runStatusPill,
        CssTheme[props.theme].runStatusPill,
        isLink ? RUN_STATUS_BORDER_CLASSES[status] : '',
        pillClassName,
      )

      const buildNumberIcon = h(StatusIcon, {
        size: iconSize,
        status,
        variant: iconVariant,
        'data-cy': 'run-status-icon',
        class: CssClasses.runStatusIcon,
      })
      const buildNumberLabel = h(
        'span',
        { class: RUN_STATUS_TEXT_CLASSES[status] },
        `#${buildNumber}`,
      )

      const hasBranch = !!branch
      const segments: VNode[] = [
        renderRunStatusSegment(
          'build-number',
          buildNumberIcon,
          buildNumberLabel,
          href,
          `View run #${buildNumber}`,
          hasBranch,
        ),
      ]
      if (hasBranch) {
        const branchIcon = h(IconTechnologyBranchH, {
          size: '16',
          strokeColor: 'gray-500',
          'data-cy': 'run-status-branch-icon',
          class: CssClasses.runStatusIcon,
        })
        const branchLabel = h(
          'span',
          {
            class: joinClasses(
              CssClasses.runStatusBranchText,
              CssTheme[props.theme].runStatusBranchText,
            ),
          },
          branch,
        )
        segments.push(
          renderRunStatusSegment(
            'branch',
            branchIcon,
            branchLabel,
            undefined,
            '',
            false,
          ),
        )
      }

      return h(
        'span',
        {
          'data-cy': 'run-status',
          title: RUN_STATUS_LABELS[status],
          class: pillClasses,
        },
        segments,
      )
    }

    return () => {
      const summaryProps = {
        passed: props.passed,
        failed: props.failed,
        skipped: props.skipped,
        pending: props.pending,
        flaky: props.flaky,
        selfHealed: props.selfHealed,
        showSelfHealed: props.showSelfHealed,
        expanded: props.expanded,
      }

      const showTestCounts = hasAnyStat(summaryProps)
      // The run-status pill only renders when `status` is a valid
      // `RunStatusKey` (see also the defense-in-depth guard in
      // `renderRunStatusPill`). Gate `showRunStatus` on the same check so a
      // `runStatus` with an invalid status doesn't produce an empty root
      // wrapper when the test-counts pill is also empty. Warn once in dev
      // when we skip due to a bad status (deduped inside `warnInvalidRunStatus`).
      const showRunStatus =
        !!props.runStatus && !!RUN_STATUS_VARIANTS[props.runStatus.status]
      if (props.runStatus && !showRunStatus) {
        warnInvalidRunStatus(props.runStatus.status)
      }

      // Both pills empty → render nothing.
      if (!showRunStatus && !showTestCounts) return null

      const separatorAfterKey = getSeparatorAfterKey(summaryProps)
      const showFlaky = statValue(props.flaky) > 0
      // Self-healed renders whenever the flag is true; the count (0 included)
      // is shown verbatim. See instructions.md / architecture.md for rationale.
      const showSelfHealedStat = !!props.showSelfHealed

      const items: VNode[] = []
      if (showFlaky) {
        items.push(
          renderStat(
            'flaky',
            statValue(props.flaky),
            props.links?.flaky,
            separatorAfterKey === 'flaky',
          ),
        )
      }
      if (showSelfHealedStat) {
        items.push(
          renderStat(
            'selfHealed',
            statValue(props.selfHealed),
            props.links?.selfHealed,
            separatorAfterKey === 'selfHealed',
          ),
        )
      }
      if (showRegularStat(props.skipped, props.expanded)) {
        items.push(
          renderStat(
            'skipped',
            statValue(props.skipped),
            props.links?.skipped,
            false,
          ),
        )
      }
      if (showRegularStat(props.pending, props.expanded)) {
        items.push(
          renderStat(
            'pending',
            statValue(props.pending),
            props.links?.pending,
            false,
          ),
        )
      }
      if (showRegularStat(props.passed, props.expanded)) {
        items.push(
          renderStat(
            'passed',
            statValue(props.passed),
            props.links?.passed,
            false,
          ),
        )
      }
      if (showRegularStat(props.failed, props.expanded)) {
        items.push(
          renderStat(
            'failed',
            statValue(props.failed),
            props.links?.failed,
            false,
          ),
        )
      }

      // The wrapper <div> is the root. Holds up to two pills:
      //   1. run-status pill (rendered when `runStatus` is set)
      //   2. test-counts pill (rendered when `hasAnyStat` is true)
      // `className` + fallthrough `attrs.class` land here. `pillClassName`
      // lands on the test-counts <ul>; `runStatus.pillClassName` lands on the
      // run-status <span>. Both merged via `tailwind-merge` so a consumer
      // override wins the Tailwind source-order conflict.
      const children: VNode[] = []
      if (showRunStatus) {
        const pill = renderRunStatusPill(props.runStatus as RunStatusConfig)
        if (pill) children.push(pill)
      }
      if (showTestCounts) {
        children.push(
          h(
            'ul',
            {
              class: twMerge(
                CssClasses.list,
                CssTheme[props.theme].list,
                props.pillClassName,
              ),
            },
            items,
          ),
        )
      }
      return h(
        'div',
        {
          ...attrs,
          'data-cy': 'run-results',
          // Array form lets Vue normalize a string/array/object fallthrough
          // `attrs.class` without manual flattening.
          class: [CssClasses.container, props.className, attrs.class],
        },
        children,
      )
    }
  },
})
</script>
