// components/TestResult/react/TestResult.tsx
import * as React from 'react'
import clsx from 'clsx'
import {
  classes,
  type TestResultData,
} from '@cypress-design/constants-testresult'
import StatusIcon from '@cypress-design/react-statusicon'
import {
  IconChevronRightSmall,
  IconStatusFlaky,
  IconDocumentModifiedSquareDot,
  IconDocumentAddedSquarePlus,
} from '@cypress-design/react-icon'

export interface TestResultProps extends TestResultData {
  className?: string
}

export const TestResult: React.FC<
  TestResultProps & React.HTMLProps<HTMLDivElement>
> = ({
  status,
  names,
  flaky,
  modified,
  added,
  groups,
  className,
  children,
}) => {
  return (
    <div
      data-cy="cd-tr-container"
      className={clsx(classes.container, className)}
    >
      <div data-cy="cd-tr-row" className={classes.row}>
        <div data-cy="cd-tr-list" className={classes.list}>
          <div data-cy="cd-tr-icon" className={classes.icon}>
            <StatusIcon
              size="16"
              variant="solid"
              status={status}
              className={classes.status_icon}
            />
          </div>
          <div
            data-cy="cd-tr-name-container-column"
            className={classes.name.container.column}
          >
            {names.slice(0, -1).length > 0 && (
              <div
                data-cy="cd-tr-name-container-describes"
                className={classes.name.container.describes}
              >
                {names.slice(0, -1).map((name, index) => (
                  <React.Fragment key={index}>
                    <div
                      data-cy="cd-tr-name-item"
                      className={clsx({
                        [classes.name.item.base]: true,
                        [classes.name.item.first]:
                          names.length >= 2 && index === 0,
                        [classes.name.item.middle]:
                          names.length >= 2 &&
                          index > 0 &&
                          index < names.length - 1,
                      })}
                    >
                      <span
                        data-cy="cd-tr-name-item-text"
                        className={classes.name.item.text.base}
                      >
                        {name}
                      </span>
                    </div>
                    {index < names.length - 1 && (
                      <div
                        data-cy="cd-tr-chevron"
                        className={classes.chevron.container}
                      >
                        <IconChevronRightSmall
                          strokeColor="gray-200"
                          className="align-top relative bottom-[-1px]"
                        />
                      </div>
                    )}
                  </React.Fragment>
                ))}
              </div>
            )}
            <div
              data-cy="cd-tr-name-container-it"
              className={classes.name.container.it}
            >
              <span
                data-cy="cd-tr-name-item-text"
                className={[
                  classes.name.item.text.base,
                  classes.name.item.text.it,
                ].join(' ')}
              >
                {names.at(-1)}
              </span>
              {(flaky || modified || added) && (
                <div
                  data-cy="cd-tr-attributes"
                  className={classes.attribute.container}
                >
                  {flaky && <IconStatusFlaky data-cy="cd-tr-flaky" />}
                  {modified && (
                    <IconDocumentModifiedSquareDot data-cy="cd-tr-modified" />
                  )}
                  {added && (
                    <IconDocumentAddedSquarePlus data-cy="cd-tr-added" />
                  )}
                </div>
              )}
            </div>
          </div>
          {children ? (
            <div data-cy="cd-tr-actions" className={classes.button.container}>
              {children}
            </div>
          ) : null}
        </div>
        {groups ? (
          <div
            data-cy="cd-tr-group-container"
            className={classes.group.container}
          >
            <div className="border border-gray-100 rounded">{groups}</div>
          </div>
        ) : null}
      </div>
    </div>
  )
}

export default TestResult

// components/TestResult/vue/TestResult.vue
<script lang="ts" setup>
import {
  classes,
  type TestResultData,
} from '@cypress-design/constants-testresult'
import { StatusIcon } from '@cypress-design/vue-statusicon'
import {
  IconChevronRightSmall,
  IconStatusFlaky,
  IconDocumentModifiedSquareDot,
  IconDocumentAddedSquarePlus,
} from '@cypress-design/vue-icon'

defineProps<TestResultData>()
</script>

<template>
  <div data-cy="cd-tr-container" :class="classes.container">
    <div data-cy="cd-tr-row" :class="classes.row">
      <div data-cy="cd-tr-list" :class="classes.list">
        <div data-cy="cd-tr-icon" :class="classes.icon">
          <StatusIcon
            size="16"
            variant="solid"
            :status="status"
            :class="classes.status_icon"
          />
        </div>
        <div
          data-cy="cd-tr-name-container-column"
          :class="classes.name.container.column"
        >
          <div
            data-cy="cd-tr-name-container-describes"
            :class="classes.name.container.describes"
            v-if="names.slice(0, -1).length > 0"
          >
            <template v-for="(name, index) in names.slice(0, -1)" :key="index">
              <div
                data-cy="cd-tr-name-item"
                :class="{
                  [classes.name.item.base]: true,
                  [classes.name.item.first]: names.length >= 2 && index === 0,
                  [classes.name.item.middle]:
                    names.length >= 2 && index > 0 && index < names.length - 1,
                }"
              >
                <span
                  data-cy="cd-tr-name-item-text"
                  :class="classes.name.item.text.base"
                  >{{ name }}</span
                >
              </div>
              <div
                data-cy="cd-tr-chevron"
                :class="classes.chevron.container"
                v-if="index < names.length - 1"
              >
                <IconChevronRightSmall
                  stroke-color="gray-200"
                  class="align-top relative bottom-[-1px]"
                />
              </div>
            </template>
          </div>
          <div
            data-cy="cd-tr-name-container-it"
            :class="classes.name.container.it"
          >
            <span
              data-cy="cd-tr-name-item-text"
              :class="[classes.name.item.text.base, classes.name.item.text.it]"
            >
              {{ names.at(-1) }}
            </span>
            <div
              data-cy="cd-tr-attributes"
              :class="classes.attribute.container"
              v-if="flaky || modified || added"
            >
              <IconStatusFlaky data-cy="cd-tr-flaky" v-if="flaky" />
              <IconDocumentModifiedSquareDot
                data-cy="cd-tr-modified"
                v-if="modified"
              />
              <IconDocumentAddedSquarePlus data-cy="cd-tr-added" v-if="added" />
            </div>
          </div>
        </div>
        <div
          v-if="$slots.actions"
          data-cy="cd-tr-actions"
          :class="classes.button.container"
        >
          <slot name="actions" />
        </div>
      </div>
      <div
        v-if="$slots.groups?.() !== undefined"
        data-cy="cd-tr-group-container"
        :class="classes.group.container"
      >
        <slot name="groups" />
      </div>
    </div>
  </div>
</template>
