// components/Button/vue/Button.vue
<template>
  <button :class="[
    StaticClasses,
    VariantClassesTable[finalVariant],
    SizeClassesTable[size],
  ]" :disabled="finalDisabled">
    <slot />
  </button>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import {
  VariantClassesTable,
  SizeClassesTable,
  StaticClasses,
} from '../constants'
import type { ButtonProps } from '../constants'

const props = withDefaults(
  defineProps<ButtonProps>(),
  {
    variant: 'indigo-dark',
    size: '32',
    disabled: false,
  }
)

const finalVariant = computed(() =>
  props.disabled &&
    !['outline-dark', 'outline-light', 'link'].includes(props.variant)
    ? 'disabled'
    : props.variant
)
const finalDisabled = computed(
  () => props.disabled || props.variant === 'disabled'
)
</script>

// components/Button/react/Button.tsx
import clsx from 'clsx'
import * as React from 'react'
import type { ButtonProps } from '../constants'
import {
  SizeClassesTable,
  VariantClassesTable,
  StaticClasses,
} from '../constants'

export interface ButtonPropsJsx extends ButtonProps {
  className?: string
  children?: React.ReactNode
}

export const Button: React.FC<
  ButtonPropsJsx & Omit<React.HTMLProps<HTMLButtonElement>, 'size'>
> = ({
  variant = 'indigo-dark',
  size = '32',
  disabled = false,
  className,
  children,
  ...rest
}) => {
  const finalVariant =
    disabled && !['outline-dark', 'outline-light', 'link'].includes(variant)
      ? 'disabled'
      : variant
  const finalDisabled = disabled || variant === 'disabled'
  return (
    <button
      {...rest}
      type="button"
      className={clsx(
        StaticClasses,
        VariantClassesTable[finalVariant],
        SizeClassesTable[size],
        className
      )}
      disabled={finalDisabled}
    >
      {children}
    </button>
  )
}

export default Button
