// components/Tooltip/vue/Tooltip.vue
<template>
  <div
    ref="reference"
    @mouseover="placeTooltip"
    @focus="placeTooltip"
    @blur="show = false"
    @mouseout="show = false"
  >
    <slot />
    <teleport to="#portal-target">
      <div
        v-if="!disabled"
        @mouseover="tooltipHovered = true"
        @mouseout="tooltipHovered = false"
        role="tooltip"
        ref="tooltip"
        :style="
          positionComputed
            ? `top:${top}px!important;left:${left}px!important;`
            : undefined
        "
        class="absolute p-16px"
        :class="{
          invisible:
            !show && positionComputed && !(tooltipHovered && interactive),
          '-top-10000px invisible': !positionComputed,
        }"
      >
        <div
          class="rounded shadow border"
          :class="[colors.background, colors.block]"
        >
          <svg
            ref="arrowRef"
            viewBox="0 0 48 48"
            width="24"
            height="24"
            class="absolute z-10"
            :class="colors.svg"
            :style="`transform: rotate(${arrowRotate}deg); filter: ${dropShadowFilter};${arrowYRule}:${arrowTop}px!important;${arrowXRule}:${arrowLeft}px!important;`"
            fill="none"
          >
            <rect
              x="0"
              y="-4"
              width="48"
              height="8"
              stroke-width="0"
              stroke-color="red"
            />
            <path
              d="M 0 3 C 12 3 18 18 24 18 C 30 18 36 3 48 3"
              stroke-width="2"
            />
          </svg>
          <div
            class="rounded text-16px leading-24px min-w-160px text-center p-8px relative z-20"
            :class="colors.background"
          >
            <slot name="popper" />
          </div>
        </div>
      </div>
    </teleport>
  </div>
</template>

<script lang="ts" setup>
import type { Placement, Side } from '@floating-ui/dom'
import { computePosition, flip, offset, arrow } from '@floating-ui/dom'
import type { Ref } from 'vue'
import { computed, ref, onBeforeMount } from 'vue'

const props = withDefaults(
  defineProps<{
    /**
     * Where the tooltip should be placed relative to the target.
     */
    placement?: Placement
    /**
     * Background color of the tooltip.
     */
    color?: 'light' | 'dark'
    /**
     * Disable the tooltip.
     * This hides the popper and makes the tooltip inactive.
     */
    disabled?: boolean
    /**
     * If true, the tooltip will be hidden when hovering the popper/tooltip
     */
    interactive?: boolean
    /**
     * If set, the tooltip will always respect the given placement
     */
    forcePlacement?: boolean
  }>(),
  {
    color: 'light',
  }
)

const portalTarget: Ref<HTMLElement | null> = ref(null)
const reference: Ref<HTMLElement | null> = ref(null)
const tooltip: Ref<HTMLElement | null> = ref(null)
const arrowRef: Ref<HTMLElement | null> = ref(null)
const left = ref(0)
const top = ref(0)
const arrowLeft = ref(0)
const arrowTop = ref(0)
const arrowRotate = ref(0)
const arrowXRule: Ref<'left' | 'right'> = ref('left')
const arrowYRule: Ref<'top' | 'bottom'> = ref('top')
const positionComputed = ref(false)
const dropShadowFilter: Ref<string | undefined> = ref(undefined)
const placementSideFinal = ref(props.placement)
const show = ref(false)
const tooltipHovered = ref(false)

const ROTATE_MAP = {
  bottom: 180,
  left: 270,
  top: 0,
  right: 90,
} as const

onBeforeMount(async () => {
  await getTarget()
})

async function getTarget() {
  let portalTargetLocal = document.getElementById('portal-target')
  if (!portalTargetLocal) {
    portalTargetLocal = document.createElement('div')
    portalTargetLocal.id = 'portal-target'
    document.body.appendChild(portalTargetLocal)
  }
  portalTarget.value = portalTargetLocal
}

const colors = computed(() => {
  switch (props.color) {
    case 'light':
      return {
        svg: 'stroke-none fill-white',
        block: 'text-gray-900 shadow-gray-100 border-transparent',
        background: 'bg-white',
      }
    case 'dark':
      return {
        svg: 'stroke-none fill-gray-900',
        block: 'text-white shadow-gray-800 border-transparent',
        background: 'bg-gray-900',
      }
    default:
      return {}
  }
})

async function placeTooltip() {
  if (props.disabled || !reference.value || !tooltip.value || !arrowRef.value)
    return
  const {
    x,
    y,
    placement,
    middlewareData: { arrow: { x: arrowX, y: arrowY } = {} },
  } = await computePosition(reference.value, tooltip.value, {
    placement: props.placement,
    middleware: [
      props.forcePlacement
        ? {
            name: 'no-flip',
            fn: (obj) => obj,
          }
        : flip(),
      offset(0),
      arrow({ element: arrowRef.value, padding: 24 }),
    ],
  })
  left.value = x
  top.value = y
  const placementSide = placement.split('-')[0] as Side
  arrowRotate.value = ROTATE_MAP[placementSide]

  dropShadowFilter.value =
    placementSide === 'bottom' || props.color === 'dark'
      ? 'drop-shadow(0 1px 1px rgba(225, 227, 237, .3))'
      : 'drop-shadow(0 1px 1px rgba(225, 227, 237, .8))'

  if (arrowX && arrowY) {
    arrowLeft.value = arrowX
    arrowTop.value = arrowY
    arrowXRule.value = 'left'
    arrowYRule.value = 'top'
  } else if (arrowX) {
    arrowLeft.value = arrowX
    arrowTop.value = -6
    arrowXRule.value = 'left'
    arrowYRule.value = placementSide === 'top' ? 'bottom' : 'top'
  } else if (arrowY) {
    arrowTop.value = arrowY
    arrowLeft.value = -6
    arrowXRule.value = placementSide === 'left' ? 'right' : 'left'
    arrowYRule.value = 'top'
  }
  positionComputed.value = true
  placementSideFinal.value = placementSide

  show.value = true
}
</script>

// components/Tooltip/react/Tooltip.tsx
import clsx from 'clsx'
import * as React from 'react'
import {
  Placement,
  offset,
  flip,
  arrow,
  shift,
  autoUpdate,
  useFloating,
  useInteractions,
  useHover,
  useFocus,
  useRole,
  useDismiss,
  safePolygon,
  FloatingPortal,
} from '@floating-ui/react-dom-interactions'

export interface TooltipProps {
  /**
   * Where the tooltip should be placed relative to the target.
   */
  placement?: Placement
  /**
   * background color of the tooltip.
   */
  color?: 'light' | 'dark'
  className?: string
  children?: React.ReactNode
  /**
   * The content of the tooltip.
   */
  popper?: React.ReactNode
  /**
   * Disable the tooltip.
   * This hides the popper and makes the tooltip inactive.
   */
  disabled?: boolean
  /**
   * If true, the tooltip will be hidden when hovering the popper/tooltip
   */
  interactive?: boolean
  /**
   * If set, the tooltip will always respect the given placement
   */
  forcePlacement?: boolean
  /**
   * Make sure the tooltip stays always open.
   * This is useful for debugging.
   */
  forceOpen?: boolean
}

const ROTATE_MAP = {
  bottom: 180,
  left: 270,
  top: 0,
  right: 90,
}

export const Tooltip: React.FC<
  TooltipProps & React.HTMLProps<HTMLDivElement>
> = ({
  placement,
  color = 'light',
  className,
  children,
  popper,
  disabled,
  interactive,
  forcePlacement,
  forceOpen = false,
  ...rest
}) => {
  const arrowRef = React.useRef(null)
  const [open, setOpen] = React.useState(false)

  React.useEffect(() => {
    if (forceOpen) {
      setOpen(true)
    }
  }, [forceOpen])

  const {
    x,
    y,
    reference,
    floating,
    strategy,
    placement: calculatedPlacement,
    context,
    middlewareData: { arrow: { x: arrowX, y: arrowY } = {} },
  } = useFloating({
    placement,
    open,
    onOpenChange: setOpen,
    middleware: [
      forcePlacement
        ? {
            name: 'no-flip',
            fn: (obj) => obj,
          }
        : flip(),
      offset(interactive ? 0 : 16),
      arrow({ element: arrowRef, padding: 24 }),
      shift({ padding: 16 }),
    ],
    whileElementsMounted: autoUpdate,
  })

  const contextHook = useDismiss(context)

  const { getReferenceProps, getFloatingProps } = useInteractions([
    useHover(context, {
      handleClose: interactive ? safePolygon() : undefined,
      enabled: !disabled && !forceOpen,
    }),
    useFocus(context, {
      enabled: !disabled && !forceOpen,
    }),
    useRole(context, { role: 'tooltip' }),
    ...(!forceOpen ? [contextHook] : []),
  ])

  const placementSide = calculatedPlacement.split(
    '-',
  )[0] as keyof typeof ROTATE_MAP
  const arrowRotate = ROTATE_MAP[placementSide]

  let arrowXRule = 'left',
    arrowYRule = 'top'

  if (arrowX && arrowY) {
    arrowXRule = 'left'
    arrowYRule = 'top'
  } else if (arrowX) {
    arrowXRule = 'left'
    arrowYRule = placementSide === 'top' ? 'bottom' : 'top'
  } else if (arrowY) {
    arrowXRule = placementSide === 'left' ? 'right' : 'left'
    arrowYRule = 'top'
  }

  const getColors = () => {
    switch (color) {
      case 'light':
        return {
          svg: 'stroke-none fill-white',
          block: 'text-gray-900 border-transparent',
          background: 'bg-white',
        }
      case 'dark':
        return {
          svg: 'stroke-none fill-gray-900',
          block: 'text-white border-transparent',
          background: 'bg-gray-900',
        }
      default:
        return {}
    }
  }

  const colors = getColors()

  return (
    <>
      <div
        {...getReferenceProps()}
        ref={reference}
        className={className}
        {...rest}
      >
        {children}
      </div>
      {disabled ? null : (
        <FloatingPortal>
          {open && (
            <div
              {...getFloatingProps({
                ref: floating,
                style: {
                  position: strategy,
                  top: y ?? '',
                  left: x ?? '',
                  ...(interactive ? { padding: '16px' } : {}),
                },
              })}
              role="tooltip"
            >
              <div
                className={clsx('rounded shadow-tooltip border', [
                  colors.background,
                  colors.block,
                  (!x || !y) && 'invisible',
                ])}
              >
                <svg
                  ref={arrowRef}
                  viewBox="0 0 48 24"
                  width="24"
                  height="12"
                  className={clsx('absolute z-10', colors.svg)}
                  style={{
                    transform: `rotate(${arrowRotate}deg)`,
                    filter:
                      placementSide === 'bottom' || color === 'dark'
                        ? 'drop-shadow(0 1px 1px rgba(225, 227, 237, .3))'
                        : 'drop-shadow(0 1px 1px rgba(225, 227, 237, .8))',
                    [arrowXRule]: `${arrowX ?? (interactive ? 0 : -16)}px`,
                    [arrowYRule]: `${
                      arrowY ? arrowY + 6 : interactive ? 6 : -10
                    }px`,
                  }}
                  fill="none"
                >
                  <rect x="0" y="0" width="48" height="4" strokeWidth="0" />
                  <path
                    d="M 0 3 C 12 3 18 18 24 18 C 30 18 36 3 48 3"
                    strokeWidth="2"
                  />
                </svg>
                <div
                  className={clsx(
                    'rounded text-[16px] leading-[24px] min-w-[160px] text-center p-[8px] relative z-20',
                    colors.background,
                  )}
                >
                  <span className="sr-only">Tooltip: </span>
                  {popper}
                </div>
              </div>
            </div>
          )}
        </FloatingPortal>
      )}
    </>
  )
}

export default Tooltip
