// docs/src/demos/Tabs/vue/BlockSwitching.vue
<script setup lang="ts">
import { ref } from 'vue'
import Tabs from '@cypress-design/vue-tabs'

const allowMove = ref(true)
const tabs = [
  {
    id: 'ov',
    label: 'Overview',
    ['aria-controls']: 'vue-block-switching-panel-1',
  },
  {
    id: 'cl',
    label: 'Command Log',
    ['aria-controls']: 'vue-block-switching-panel-2',
  },
  {
    id: 'err',
    label: 'Errors',
    tag: '13',
    ['aria-controls']: 'vue-block-switching-panel-3',
  },
  {
    id: 'reco',
    label: 'Recommendations',
    ['aria-controls']: 'vue-block-switching-panel-4',
  },
]
</script>

<template>
  <label class="mb-4 flex items-center gap-2">
    <input v-model="allowMove" type="checkbox" />
    Allow tab move
  </label>
  <!-- Calling preventDefault() in the switch handler keeps the current tab. -->
  <Tabs
    :tabs="tabs"
    active-id="ov"
    @switch="
      (_tab, e) => {
        if (!allowMove) e.preventDefault()
      }
    "
  />
</template>

// docs/src/demos/Tabs/react/BlockSwitching.tsx
import { useState } from 'react'
import Tabs from '@cypress-design/react-tabs'

const tabs = [
  {
    id: 'ov',
    label: 'Overview',
    ['aria-controls']: 'react-block-switching-panel-1',
  },
  {
    id: 'cl',
    label: 'Command Log',
    ['aria-controls']: 'react-block-switching-panel-2',
  },
  {
    id: 'err',
    label: 'Errors',
    tag: '13',
    ['aria-controls']: 'react-block-switching-panel-3',
  },
  {
    id: 'reco',
    label: 'Recommendations',
    ['aria-controls']: 'react-block-switching-panel-4',
  },
]

// Calling preventDefault() in onSwitch keeps the current tab.
export default function BlockSwitching() {
  const [allowMove, setAllowMove] = useState(true)
  return (
    <>
      <label className="mb-4 flex items-center gap-2">
        <input
          type="checkbox"
          checked={allowMove}
          onChange={(e) => setAllowMove(e.target.checked)}
        />
        Allow tab move
      </label>
      <Tabs
        tabs={tabs}
        activeId="ov"
        onSwitch={(_tab, e) => {
          if (!allowMove) e.preventDefault()
        }}
      />
    </>
  )
}
