// components/Textbox/react/Textbox.tsx
import clsx from 'clsx'
import * as React from 'react'
import {
  TextboxProps as TextboxPropsBase,
  DefaultTheme,
  DefaultVariant,
  DefaultSize,
  CssStaticClasses,
  CssInputSizeClassesTable,
  CssVariantClassesTable,
  CssRoundedClasses,
  CssInputClassesTable,
  CssLabelSizeClassesTable,
  CssLabelThemeClassesTable,
  CssLabelBorderClassesTable,
  CssLabelRoundedClassesTable,
  CssLabelBaseClasses,
  IconColors,
  DividerClasses,
  CssWrapperHeightClassesTable,
  CssInputContainerPaddingClassesTable,
  CssInputContainerBaseClasses,
  CssShrinkZeroClass,
  TextboxTheme,
  TextboxVariant,
  TextboxSize,
} from '@cypress-design/constants-textbox'

export interface TextboxPropsJsx
  extends Omit<TextboxPropsBase, 'iconLeft' | 'iconRight' | 'rounded'> {
  onClick?: (event: React.MouseEvent<HTMLElement, MouseEvent>) => void
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void
  onInput?: (event: React.FormEvent<HTMLInputElement>) => void
  onFocus?: (event: React.FocusEvent<HTMLInputElement>) => void
  onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void
  className?: string
  iconLeft?: React.ComponentType<any> | React.ReactNode
  iconRight?: React.ComponentType<any> | React.ReactNode
  type?: 'text' | 'password' | 'email' | 'search' | 'tel' | 'url'
  name?: string
  id?: string
  autoFocus?: boolean
  rounded?: boolean
  'aria-label'?: string
  'aria-invalid'?: boolean | 'false' | 'true' | 'grammar' | 'spelling'
  'aria-describedby'?: string
}

type ReactTextboxProps = TextboxPropsJsx &
  Omit<
    React.HTMLProps<HTMLInputElement>,
    | 'size'
    | 'onChange'
    | 'onInput'
    | 'onFocus'
    | 'onBlur'
    | 'type'
    | 'className'
  >

export const Textbox: React.FC<ReactTextboxProps> = ({
  theme = DefaultTheme,
  variant = DefaultVariant,
  size = DefaultSize,
  rounded = false,
  labelLeft,
  iconLeft: IconLeft,
  divider = false,
  iconRight: IconRight,
  labelRight,
  disabled = false,
  placeholder,
  value,
  defaultValue,
  className,
  onChange,
  onInput,
  onFocus,
  onBlur,
  type = 'text',
  'aria-label': ariaLabel,
  'aria-invalid': ariaInvalid,
  'aria-describedby': ariaDescribedBy,
  ...rest
}) => {
  // Determine state key for variant classes
  // States are handled by CSS pseudo-classes (hover, active, focus, focus-visible, placeholder-shown)
  // We only need to determine base state: disabled or default
  // CSS will automatically apply hover/active/focus/focus-visible/placeholder-shown styles
  const stateKey: 'default' | 'disabled' = disabled ? 'disabled' : 'default'

  // Build variant class key: theme-variant-state
  const variantKey =
    `${theme}-${variant}-${stateKey}` as keyof typeof CssVariantClassesTable

  // Get variant classes - these include hover/active/focus/focus-visible styles
  // CSS pseudo-classes will automatically apply the correct styles
  const variantClasses = CssVariantClassesTable[variantKey] || ''

  // Get rounded classes
  const roundedClasses =
    CssRoundedClasses[rounded as unknown as keyof typeof CssRoundedClasses]

  // Build wrapper classes - wrapper handles hover/focus states and height
  const wrapperClasses = clsx(
    CssStaticClasses,
    variantClasses,
    roundedClasses,
    CssWrapperHeightClassesTable[size], // Height on wrapper
    className,
  )

  // Build input container classes - this contains the input and icons with padding
  const inputContainerClasses = clsx(
    CssInputContainerBaseClasses,
    CssInputContainerPaddingClassesTable[size], // Padding on input container
  )

  // Get input size classes (font size and line height)
  const inputSizeClasses = CssInputSizeClassesTable[size]

  // Build input classes
  const inputClasses = clsx(CssInputClassesTable[theme], inputSizeClasses)

  // Get icon colors based on current state
  // For hover/active/focus-visible/placeholder-shown, CSS will handle the transitions
  // We use the base state (default) for icon colors
  const iconStateKey = disabled ? 'disabled' : 'default'
  const iconColorKey =
    `${theme}-${variant}-${iconStateKey}` as keyof typeof IconColors
  const iconColors = IconColors[iconColorKey] || {
    strokeColor: 'gray-600',
    fillColor: 'transparent',
  }

  // Get divider classes
  const dividerClasses = DividerClasses[theme]

  // Render icon helper
  const renderIcon = (
    Icon: React.ComponentType<any> | React.ReactNode | undefined,
  ) => {
    if (!Icon) return null

    // If Icon is a React component
    if (typeof Icon === 'function' || React.isValidElement(Icon)) {
      const IconComponent = Icon as React.ComponentType<any>
      return (
        <IconComponent
          size="16"
          strokeColor={iconColors.strokeColor}
          fillColor={iconColors.fillColor}
          className={CssShrinkZeroClass}
        />
      )
    }

    // If Icon is already a ReactNode
    return <span className={CssShrinkZeroClass}>{Icon}</span>
  }

  // Determine aria-invalid value
  const ariaInvalidValue =
    ariaInvalid !== undefined
      ? ariaInvalid
      : variant === 'invalid'
        ? true
        : undefined

  return (
    <div className={wrapperClasses}>
      {/* Label Left */}
      {labelLeft && (
        <span
          className={clsx(
            CssLabelBaseClasses,
            CssLabelSizeClassesTable[size],
            CssLabelThemeClassesTable[theme],
            CssLabelBorderClassesTable.left[theme],
            CssLabelRoundedClassesTable.left[
              rounded ? 'rounded' : 'notRounded'
            ],
          )}
        >
          {labelLeft}
        </span>
      )}

      {/* Input Container - contains icons and input */}
      <div className={inputContainerClasses}>
        {/* Icon Left */}
        {renderIcon(IconLeft)}

        {/* Divider */}
        {divider && IconLeft && (
          <div className={clsx(dividerClasses, CssShrinkZeroClass)} />
        )}

        {/* Input */}
        <input
          type={type}
          className={inputClasses}
          value={value}
          defaultValue={defaultValue}
          disabled={disabled}
          placeholder={placeholder}
          onChange={onChange}
          onInput={onInput}
          onFocus={onFocus}
          onBlur={onBlur}
          aria-label={ariaLabel}
          aria-invalid={ariaInvalidValue}
          aria-describedby={ariaDescribedBy}
          {...rest}
        />

        {/* Icon Right */}
        {renderIcon(IconRight)}
      </div>

      {/* Label Right */}
      {labelRight && (
        <span
          className={clsx(
            CssLabelBaseClasses,
            CssLabelSizeClassesTable[size],
            CssLabelThemeClassesTable[theme],
            CssLabelBorderClassesTable.right[theme],
            CssLabelRoundedClassesTable.right[
              rounded ? 'rounded' : 'notRounded'
            ],
          )}
        >
          {labelRight}
        </span>
      )}
    </div>
  )
}

export default Textbox

// components/Textbox/vue/Textbox.vue
<script lang="ts">
import { PropType, computed, defineComponent } from 'vue'
import {
  DefaultTheme,
  DefaultVariant,
  DefaultSize,
  CssStaticClasses,
  CssInputSizeClassesTable,
  CssVariantClassesTable,
  CssRoundedClasses,
  CssInputClassesTable,
  CssLabelSizeClassesTable,
  CssLabelThemeClassesTable,
  CssLabelBorderClassesTable,
  CssLabelRoundedClassesTable,
  CssLabelBaseClasses,
  IconColors,
  DividerClasses,
  type TextboxTheme,
  type TextboxVariant,
  type TextboxSize,
} from '@cypress-design/constants-textbox'

export default defineComponent({
  name: 'Textbox',
  props: {
    theme: {
      type: String as PropType<TextboxTheme>,
      default: DefaultTheme,
    },
    variant: {
      type: String as PropType<TextboxVariant>,
      default: DefaultVariant,
    },
    size: {
      type: String as PropType<TextboxSize>,
      default: DefaultSize,
    },
    rounded: {
      type: Boolean,
      default: false,
    },
    labelLeft: {
      type: [String, Object] as PropType<string | unknown>,
    },
    iconLeft: {
      type: [Object, Function] as PropType<unknown>,
    },
    divider: {
      type: Boolean,
      default: false,
    },
    iconRight: {
      type: [Object, Function] as PropType<unknown>,
    },
    labelRight: {
      type: [String, Object] as PropType<string | unknown>,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    placeholder: {
      type: String,
    },
    modelValue: {
      type: String,
      default: '',
    },
    value: {
      type: String,
    },
    type: {
      type: String as PropType<
        'text' | 'password' | 'email' | 'search' | 'tel' | 'url'
      >,
      default: 'text',
    },
    name: {
      type: String,
    },
    id: {
      type: String,
    },
    autofocus: {
      type: Boolean,
      default: false,
    },
    'aria-label': {
      type: String,
    },
    'aria-invalid': {
      type: [Boolean, String] as PropType<
        boolean | 'false' | 'true' | 'grammar' | 'spelling'
      >,
    },
    'aria-describedby': {
      type: String,
    },
  },
  emits: {
    'update:modelValue': (value: string) => typeof value === 'string',
    input: (event: Event) => event instanceof Event,
    focus: (event: FocusEvent) => event instanceof FocusEvent,
    blur: (event: FocusEvent) => event instanceof FocusEvent,
  },
  setup(props, { emit }) {
    // Determine state key for variant classes
    // States are handled by CSS pseudo-classes (hover, active, focus, focus-visible, placeholder-shown)
    // We only need to determine base state: disabled or default
    // CSS will automatically apply hover/active/focus/focus-visible/placeholder-shown styles
    const stateKey: 'default' | 'disabled' = props.disabled
      ? 'disabled'
      : 'default'

    // Build variant class key: theme-variant-state
    const variantKey = computed(() => {
      return `${props.theme}-${props.variant}-${stateKey}` as keyof typeof CssVariantClassesTable
    })

    // Get variant classes
    const variantClasses = computed(() => {
      return CssVariantClassesTable[variantKey.value] || ''
    })

    // Extract padding and height from size
    const paddingClass = computed(() => {
      return props.size === '32' ? 'px-[12px]' : 'px-[16px]'
    })

    const heightClass = computed(() => {
      return props.size === '32'
        ? 'h-[32px]'
        : props.size === '40'
          ? 'h-[40px]'
          : 'h-[48px]'
    })

    // Get rounded classes
    const roundedClasses = computed(() => {
      return CssRoundedClasses[
        props.rounded as unknown as keyof typeof CssRoundedClasses
      ]
    })

    // Build wrapper classes
    const wrapperClasses = computed(() => {
      return [
        CssStaticClasses,
        variantClasses.value,
        roundedClasses.value,
        heightClass.value,
        'group',
      ]
    })

    // Build input container classes
    const inputContainerClasses = computed(() => {
      return ['flex-1 flex items-center gap-[12px] min-w-0', paddingClass.value]
    })

    // Get input size classes (font size and line height)
    const inputSizeClasses = computed(() => {
      return CssInputSizeClassesTable[props.size]
    })

    // Build input classes
    const inputClasses = computed(() => {
      return [CssInputClassesTable[props.theme], inputSizeClasses.value]
    })

    // Get icon colors based on current state
    // For hover/active/focus-visible/placeholder-shown, CSS will handle the transitions
    // We use the base state (default) for icon colors
    const iconStateKey = props.disabled ? 'disabled' : 'default'
    const iconColorKey = computed(() => {
      return `${props.theme}-${props.variant}-${iconStateKey}` as keyof typeof IconColors
    })

    const iconColors = computed(() => {
      return (
        IconColors[iconColorKey.value] || {
          strokeColor: 'gray-600',
          fillColor: 'transparent',
        }
      )
    })

    // Get divider classes
    const dividerClasses = computed(() => {
      return DividerClasses[props.theme]
    })

    // Determine aria-invalid value
    const ariaInvalidValue = computed(() => {
      if (props['aria-invalid'] !== undefined) {
        return props['aria-invalid']
      }
      return props.variant === 'invalid' ? true : undefined
    })

    // Get aria-label and aria-describedby from props
    const ariaLabel = computed(() => props['aria-label'])
    const ariaDescribedBy = computed(() => props['aria-describedby'])

    // Compute input value: use value prop if provided (uncontrolled), otherwise use modelValue (controlled)
    const inputValue = computed(() => {
      return props.value ?? props.modelValue ?? ''
    })

    // Handle input event
    const handleInput = (event: Event) => {
      const target = event.target as HTMLInputElement
      const newValue = target.value
      emit('update:modelValue', newValue)
      emit('input', event)
      // Value is automatically tracked via modelValue prop in Vue
    }

    // Icon props for left and right icons
    const iconLeftProps = computed(() => {
      if (!props.iconLeft) return null
      return {
        size: '16',
        strokeColor: iconColors.value.strokeColor,
        fillColor: iconColors.value.fillColor,
        class: 'shrink-0',
      }
    })

    const iconRightProps = computed(() => {
      if (!props.iconRight) return null
      return {
        size: '16',
        strokeColor: iconColors.value.strokeColor,
        fillColor: iconColors.value.fillColor,
        class: 'shrink-0',
      }
    })

    const handleFocus = (event: FocusEvent) => {
      emit('focus', event)
    }

    const handleBlur = (event: FocusEvent) => {
      emit('blur', event)
    }

    return {
      wrapperClasses,
      inputContainerClasses,
      inputClasses,
      iconColors,
      dividerClasses,
      ariaInvalidValue,
      ariaLabel,
      ariaDescribedBy,
      inputValue,
      handleInput,
      handleFocus,
      handleBlur,
      iconLeftProps,
      iconRightProps,
      // Label constants for template
      CssLabelBaseClasses,
      CssLabelSizeClassesTable,
      CssLabelThemeClassesTable,
      CssLabelBorderClassesTable,
      CssLabelRoundedClassesTable,
    }
  },
})
</script>

<template>
  <div :class="wrapperClasses">
    <!-- Label Left -->
    <span
      v-if="labelLeft"
      :class="[
        CssLabelBaseClasses,
        CssLabelSizeClassesTable[size],
        CssLabelThemeClassesTable[theme],
        CssLabelBorderClassesTable.left[theme],
        CssLabelRoundedClassesTable.left[rounded ? 'rounded' : 'notRounded'],
      ]"
    >
      {{ labelLeft }}
    </span>

    <!-- Input Container -->
    <div :class="inputContainerClasses">
      <!-- Icon Left -->
      <component :is="iconLeft" v-if="iconLeft" v-bind="iconLeftProps" />

      <!-- Divider -->
      <div v-if="divider && iconLeft" :class="[dividerClasses, 'shrink-0']" />

      <!-- Input -->
      <input
        :id="id"
        :type="type"
        :class="inputClasses"
        :value="inputValue"
        :disabled="disabled"
        :placeholder="placeholder"
        :name="name"
        :autofocus="autofocus"
        :aria-label="ariaLabel"
        :aria-invalid="ariaInvalidValue"
        :aria-describedby="ariaDescribedBy"
        @input="handleInput"
        @focus="handleFocus"
        @blur="handleBlur"
      />

      <!-- Icon Right -->
      <component :is="iconRight" v-if="iconRight" v-bind="iconRightProps" />
    </div>

    <!-- Label Right -->
    <span
      v-if="labelRight"
      :class="[
        CssLabelBaseClasses,
        CssLabelSizeClassesTable[size],
        CssLabelThemeClassesTable[theme],
        CssLabelBorderClassesTable.right[theme],
        CssLabelRoundedClassesTable.right[rounded ? 'rounded' : 'notRounded'],
      ]"
    >
      {{ labelRight }}
    </span>
  </div>
</template>
