// components/DocMenu/react/DocMenu.tsx
import * as React from 'react'
import { NavGroup, classes, NavItemLink } from '../constants'
import { DocLink } from './_DocLink'
import { DocGroup } from './_DocGroup'

export type NavItem = NavGroup | NavItemLink

export interface DocMenuProps {
  items: NavItem[]
  depth?: number
}

export const DocMenu: React.FC<DocMenuProps> = ({ items }) => {
  return (
    <ul className={classes.docMenu}>
      {items.map((item, index) =>
        'href' in item ? (
          <DocLink key={index} item={item} />
        ) : (
          <li key={index} className="relative">
            <DocGroup group={item} />
          </li>
        )
      )}
    </ul>
  )
}

export default DocMenu

// components/DocMenu/vue/DocMenu.vue
<script lang="ts" setup>
import type { NavGroup, NavItemLink } from '../constants'
import DocGroup from './_DocGroup.vue'
import DocLink from './_DocLink.vue'

defineProps<{
  items: (NavItemLink | NavGroup)[]
}>()
</script>

<template>
  <ul class="pl-[16px] py-[16px]">
    <template v-for="item in items">
      <DocLink v-if="'href' in item" :item="item" />
      <li v-else class="relative">
        <DocGroup :group="item" :depth="0" />
      </li>
    </template>
  </ul>
</template>
